/**
 * Career Interpretation Blocks
 *
 * Reusable, deterministic text blocks for career predictions.
 * Includes monthly-specific blocks for granular month-by-month guidance.
 */

export const CAREER_DASHA_BLOCKS = {
  saturn_active:
    "Career progress will require an extraordinary amount of patience and sustained, unwavering effort during this extended period. Saturn's influence rewards those who work diligently behind the scenes, often without expecting immediate public recognition or applause. Structured approaches to project management, meticulous attention to detail, and a willingness to handle mundane but critically important tasks will serve you exceptionally well right now. Long-term career goals benefit immensely from the strict discipline and practical realism that Saturn demands of you. You are building professional foundations that are meant to last for decades, not just seasons. While the climb may feel steep and slow, the authority and respect you earn during this time will be unshakeable. Avoid cutting corners or seeking quick promotions, as shortcuts will inevitably backfire under this energy. Embrace the grind as a necessary forge for your ultimate professional mastery.",
  jupiter_active:
    "Your professional growth is heavily supported by wisdom, continuous learning, and seeking out high-quality mentorship. This is a highly auspicious time to seek guidance from experienced, ethical colleagues and remain open to profound learning opportunities that expand your worldview. A significant expansion of your responsibilities is very likely, and roles involving teaching, counseling, advising, or public speaking are particularly favored to bring you success. Your consistently ethical approach to your work and your genuine desire to uplift others earn you deep trust from key decision-makers and stakeholders. You may find that opportunities arrive almost organically, seemingly out of nowhere, as a reward for past good karma in your professional life. Generosity with your knowledge will return to you multiplied. This is an excellent period for seeking promotions, asking for raises, or expanding your business reach.",
  mars_active:
    "Immense, dynamic energy and a fierce initiative are what drive your career forward during this fast-paced period. You are called to take bold, decisive action, but you must consciously channel your intense drive constructively to avoid unnecessary, damaging conflicts with superiors or colleagues. Competitive, high-stakes situations are exactly what bring out your best, most focused performance right now. Leadership roles, independent ventures, and highly demanding, project-driven work suit your current energetic signature perfectly. You have the stamina to work long hours and smash through obstacles that would deter others. However, you must actively avoid impulsive, hot-headed decisions that could undermine your carefully laid long-term professional plans. Strategic patience is the only thing that can balance your overwhelming desire to conquer your goals immediately.",
  venus_active:
    "Cultivating harmonious, supportive workplace relationships becomes the absolute key to unlocking your professional success. Creative fields, design-oriented projects, and highly collaborative team environments are particularly favored under this graceful influence. Your natural diplomatic skills and ability to mediate conflict will open new doors to lucrative partnerships and strategic alliances that significantly accelerate your career growth. Industries directly related to beauty, arts, hospitality, luxury goods, and public relations will see especially strong, profitable results for you. You will find that people simply want to work with you because of the pleasant, cooperative energy you bring to the table. Negotiation and client-facing roles will be areas where you naturally shine and bring in substantial value. Financial rewards during this period often come through social connections rather than solitary grinding.",
  mercury_active:
    "Exceptional communication skills, intellectual agility, and sharp analytical abilities take center stage in your professional life. This is an absolutely excellent period for high-stakes negotiations, delivering compelling presentations, and engaging in complex intellectual or strategic work. Writing, teaching, data analysis, coding, and any technology-related careers will thrive and expand significantly under this influence. You must stay sharp and meticulous with documentation, contracts, and all forms of professional correspondence, as these become your primary vehicles for career advancement. Your ability to quickly process new information and articulate clear, logical solutions makes you an invaluable asset to any team. Networking, short business trips, and continuous skill-upgrading are highly highlighted as pathways to your success.",
  rahu_active:
    "Highly unconventional, surprising, and completely out-of-the-box career paths may suddenly open up for you during this volatile period. You must be extremely cautious of taking unethical shortcuts, while simultaneously remaining highly open to radical, innovative opportunities that challenge the status quo. Technology sectors, massive foreign collaborations, and avant-garde approaches to your traditional profession are what will bring you unexpected, potentially massive breakthroughs. Networking in completely non-traditional circles, or perhaps finding mentors outside of your usual industry, could lead to shocking but highly lucrative career developments. You may feel a restless, insatiable ambition driving you to achieve more than you ever thought possible. Grounding yourself is essential to ensure that your rapid ascent is built on solid, sustainable reality rather than fleeting illusions.",
  ketu_active:
    "This marks a profound period of deep introspection and potential detachment regarding your traditional career direction and material ambitions. Past work experiences, both successes and failures, now offer incredibly valuable, almost spiritual insights for your future decisions. Careers oriented towards deep research, spirituality, healing, or uncovering hidden truths gain immense clarity and focus. You may suddenly feel profoundly detached from conventional, material career goals like titles or bonuses, which paradoxically opens invisible doors to much more fulfilling, soulful work aligned with your deeper purpose. You might feel drawn to work behind the scenes or to take a step back from the spotlight to re-evaluate what truly matters to you. Surrendering the need for external validation is your greatest professional superpower right now.",
  sun_active:
    "Your natural leadership qualities, personal charisma, and ability to command a room are powerfully highlighted. Recognition, praise, and formal honors from authority figures, executives, or government entities become much more likely when you demonstrate clear, unwavering confidence in your abilities. Roles involving high-level administration, government contracts, or highly visible public positions align perfectly with your current, radiant energy. Taking complete ownership of complex projects and standing firm in your unique expertise earns you lasting, widespread respect across your industry. You are meant to be seen and heard during this cycle; hiding in the shadows will only frustrate you. Step into the light, claim your authority, and confidently lead your team toward success.",
  moon_active:
    "High emotional intelligence, profound empathy, and intuitive understanding play a massively larger role in your professional success than raw logic right now. Actively nurturing genuine, caring relationships with your colleagues and clients creates unexpected, deeply loyal professional opportunities. Careers rooted in healthcare, human resources, hospitality, public service, and the creative arts receive incredibly favorable, protective energies. Your almost psychic, intuitive understanding of what others need before they even ask becomes your most potent professional asset. Your work environment must feel emotionally safe and supportive for you to truly thrive and be productive. Trust your gut feelings regarding business partnerships or major career changes, as your intuition is highly tuned during this cycle.",
};

export const CAREER_HOUSE_BLOCKS = {
  saturn_1st:
    "Rigid self-discipline and an unyielding commitment to excellence become your greatest professional assets. How you present yourself physically and energetically to the world affects your career outcomes significantly and immediately. Your tireless work ethic speaks volumes, and others naturally look to you as the ultimate model of reliability, perseverance, and quiet authority in times of crisis. You are building a reputation that is formidable and deeply respected.",
  saturn_10th:
    "Your professional responsibilities are set to increase significantly, perhaps feeling burdensome at times. However, the grueling hard work you invest in your core role will be noticed by higher-ups and eventually rewarded with substantial, lasting power. Authority positions and leadership roles demand your full, undivided attention. Your singular capacity to shoulder extremely heavy workloads without complaining becomes your defining, most valuable characteristic to your organization this period.",
  saturn_6th:
    "Meticulous attention to your daily work routines, schedules, and the operational minutiae of your job is absolutely essential. Your physical health and your work life require a careful, deliberate balance to prevent burnout during this demanding period. Service-oriented work, solving complex daily problems, and a relentless attention to operational details bring you gradual but incredibly steady, undeniable career advancement over time.",
  jupiter_10th:
    "You are entering a phase of excellent, highly visible prospects for major career advancement. Your professional reputation grows naturally and rapidly through your consistent ethical conduct, generosity of spirit, and big-picture thinking. Major promotions, highly prestigious assignments, and widespread public recognition for your expertise are strongly indicated and highly likely during this remarkably expansive and fortunate time in your professional life.",
  jupiter_9th:
    "Pursuing higher education, advanced certifications, or seeking foreign business opportunities will vastly benefit your long-term career trajectory. You must actively expand your professional horizons through continuous, dedicated learning. Academic pursuits, leading international projects, and engaging in philosophical or legal endeavors significantly enhance your professional standing and open doors to global networks.",
  jupiter_2nd:
    "Your raw income potential and ability to generate wealth increase substantially through your dedicated professional efforts. You must actively invest time and money into acquiring new skills that directly increase your market value. Supreme financial wisdom, excellent resource management, and the ability to articulate your true worth become central, driving factors in your overall career growth trajectory and financial success.",
  mars_10th:
    "A fierce, relentless competitive drive heavily fuels your highest professional ambitions right now. You must consciously channel this explosive energy into achieving concrete, measurable goals rather than engaging in petty workplace disputes. Your unique ability to take rapid, decisive action and lead teams effectively under intense pressure sets you far apart from your peers and catches the eye of top executives.",
  mars_6th:
    "You are operating in a highly competitive, fast-paced work environment that requires sharp, strategic navigation and tactical thinking. Your robust physical stamina directly supports your ability to maintain exceptionally high daily productivity. Tackling difficult challenges head-on and aggressively overcoming stubborn workplace obstacles builds your professional reputation as a fearless, indispensable problem solver.",
  venus_10th:
    "Your public professional image benefits immensely from your natural grace, charm, and elite diplomacy skills. Creative professions, luxury markets, and the arts see particularly strong, highly lucrative results. Your refined aesthetic sensibility and exceptional people skills create massive, high-paying opportunities in client-facing roles, sales, and creative leadership positions where relationship-building is paramount.",
  sun_10th:
    "Taking on supreme authority and highly visible leadership roles are your natural, destined paths right now. High-level recognition, awards, or lucrative contracts from government bodies or massive multinational organizations are highly possible. Your innate ability to command deep respect, project unwavering competence, and inspire confidence makes this an excellent, defining period for your ultimate career ascension.",
  mercury_10th:
    "Careers heavily based on communication, data, and information exchange will absolutely thrive. Your sharp analytical abilities and quick wit are highly recognized, deeply valued, and sought after by leadership. Writing, strategic consulting, software development, technology sectors, and all knowledge-sharing or educational roles bring you significant, rapid professional rewards and intellectual satisfaction.",
  rahu_10th:
    "Massive, overly ambitious career goals are suddenly within your reach, often achieved through highly unconventional or surprisingly modern means. Bleeding-edge technology, artificial intelligence, and extensive foreign connections play a major, defining role in your success. Bold, innovative, and slightly rebellious approaches to your profession attract massive attention and open entirely new, lucrative pathways for you.",
};

export const CAREER_SIGN_BLOCKS = {
  saturn_capricorn:
    "Highly structured, deeply traditional, and hierarchical career paths are heavily favored for your ultimate success. Upper-level management, strict administrative roles, and executive positions suit your temperament perfectly. Corporate leadership, leading massive institutional roles, and holding positions that require absolute authority, organization, and a respect for established protocol align seamlessly with your greatest strengths.",
  saturn_aquarius:
    "Driving systemic innovation from within large, established systems creates substantial, high-level opportunities for you. The technology sector, large-scale humanitarian fields, and progressive scientific research benefit immensely from your input. Your unique, powerful ability to merge highly progressive, humanitarian ideas with strict structural discipline and operational efficiency becomes your ultimate, unbeatable unique advantage.",
  jupiter_sagittarius:
    "Roles involving higher-level teaching, international publishing, and global, cross-cultural work expand naturally and abundantly for you. Your deeply philosophical, optimistic approach to business inspires and uplifts everyone around you. Leading cross-cultural projects, engaging in international trade, and stepping into educational leadership roles bring you profound personal fulfillment and massive professional growth.",
  jupiter_pisces:
    "Your deep intuition and seemingly psychic insights guide your complex career decisions wisely and profitably. Highly creative, imaginative, and deeply healing professions align perfectly with your compassionate nature. Work in holistic wellness, advanced spirituality, the fine arts, music, or leading major charitable organizations brings you not only deep professional satisfaction but also significant material support.",
  mars_aries:
    "Independent entrepreneurial ventures, startups, and aggressive leadership roles suit your fiery nature perfectly. Your pioneering, fearless spirit heavily drives your rapid professional success. Starting bold new initiatives from scratch, leading small, agile teams into battle, and aggressively breaking into entirely new, untested markets come naturally to you and yield the highest rewards.",
  mars_scorpio:
    "Deep research, corporate investigation, and profound transformational or crisis-management work absolutely thrive under your command. Your intense, penetrating focus creates massive, industry-changing breakthroughs. Careers in deep psychology, forensics, high-level finance, emergency medicine, and strategic corporate consulting leverage your deep, unparalleled analytical abilities to their maximum potential.",
};

export const CAREER_PERSONAL_YEAR_BLOCKS: Record<number, string> = {
  1: "This represents a definitive, powerful year of decisive action, bold initiative, and planting new professional seeds. It is the absolute perfect time for launching entirely new business ventures, aggressively seeking major promotions, or braving a completely new, uncharted career path. Taking the lead and refusing to wait for permission brings you undeniable success. Fresh, innovative ideas and taking calculated, bold risks define your upward professional trajectory this year. You are the architect of your destiny right now; do not rely on others to build it for you. Independence and self-reliance are your watchwords.",
  2: "Your overall career progress relies heavily on deep collaboration, refined diplomacy, and strategic patience. You must actively focus on networking, supporting the goals of others, and working harmoniously within teams rather than seeking solitary glory or the spotlight. In all your projects, the fine details matter immensely. Building strong, loyal alliances and actively strengthening your professional relationships yields massive, long-term dividends. Do not force outcomes; instead, create environments where success can naturally cultivate. Mediate disputes and become the indispensable glue that holds your professional network together.",
  3: "Your natural creativity, charisma, and communication skills are highly highlighted and in great demand. You must express your unique ideas boldly, loudly, and without hesitation. Careers in marketing, public relations, writing, and all artistic or performance pursuits are particularly favored and profitable this year. Your innate ability to present complex ideas engagingly and persuasively opens massive doors to new opportunities and brings you highly favorable public visibility. Socialize, network, and let your enthusiasm be contagious. Your positive energy is your greatest professional magnet right now.",
  4: "Intense, grinding hard work and unwavering discipline are absolutely required of you this year. This is a crucial, foundational building year—your complete focus must be on establishing solid foundations, creating efficient systems, and optimizing your organizational methods. Under no circumstances should you cut corners or seek easy ways out. Establishing rock-solid, reliable processes and demonstrating unshakeable reliability to your superiors earns you permanent trust and perfectly positions you for massive future advancement. Embrace the routine and find satisfaction in a job thoroughly and perfectly executed.",
  5: "Massive, unpredictable change is in the air, bringing a whirlwind of activity. You must expect unexpected, exciting opportunities or sudden, radical shifts in your professional direction. Extensive travel, relocation, or the rapid adoption of new, disruptive technologies may play a highly significant role in your work. Absolute adaptability and quick thinking are your greatest assets right now. Willingly embracing chaos and disruption leads to the most exciting, liberating professional breakthroughs of your life. Do not cling to the past; ride the wave of innovation into your future.",
  6: "Your professional responsibilities increase significantly, requiring a mature, balanced approach. Loving service to others, mentorship, and maintaining highly harmonious workplace relationships lead directly to your advancement. This is an exceptionally good time for assuming team leadership or human resources roles. Your deeply nurturing approach to management, combined with your genuine willingness to support your colleagues' well-being, builds an incredibly strong, universally respected professional reputation. Focus on creating beauty, balance, and fairness in your professional environment.",
  7: "This is a quiet, profound period meant for deep analysis, intense study, and serious skill development. Thorough research, academic study, and deep specialization are heavily favored over aggressive financial expansion or seeking the spotlight. You must listen closely to your intuition rather than just market trends. Deepening your technical expertise, retreating to plan your next moves, and pursuing advanced, specialized training creates an unshakeable, expert foundation for your future career leaps. Do the quiet work now so you can shine brilliantly later.",
  8: "This is the ultimate year of raw power, material achievement, and significant financial harvest. Massive commercial success, top-tier executive management roles, and substantial financial gains are entirely within your reach if you boldly assert yourself and claim your worth. High-level strategic thinking, understanding power dynamics, and taking decisive, confident action in complex business matters bring you substantial material rewards and widespread industry recognition. Focus on efficiency, authority, and building true wealth.",
  9: "You have reached the completion of a major nine-year professional cycle. It is crucial to finish existing, lingering projects and mentally prepare for the entirely new phase approaching. You must ruthlessly clear out what no longer serves your professional growth—be it outdated skills, toxic partnerships, or unfulfilling jobs. Engaging in humanitarian work, philanthropy, and finalizing your legacy projects bring you deep, soulful satisfaction and perfectly prepare the energetic ground for the massive fresh start awaiting you next year. Let go with grace.",
};

/** Monthly career tone modifiers — planet-influenced nuances per month */
export const CAREER_MONTHLY_BLOCKS: Record<number, string> = {
  1: "January brings a necessary, serious period of deep planning, structural organization, and highly strategic review. You must lay out your comprehensive professional roadmap and set firm milestones for the entire year ahead. Brutally evaluate your past performance and set clear, highly measurable goals. Attending key networking events and exclusive industry gatherings offer incredibly valuable, high-level connections that will quietly shape your trajectory for months to come. Do not rush; build the blueprint first.",
  2: "February demands strategic patience and quiet observation in all your career matters. You should focus on building deep relationships with key, influential stakeholders and focus heavily on meticulous, behind-the-scenes preparation for upcoming launches. Collaborative, team-based projects gain significant, undeniable momentum when you invest the extra time into truly understanding your team's unique strengths and aligning everyone's goals effectively. Wait for the right moment to strike.",
  3: "March intensely ignites your raw professional energy and ambition. You must actively take aggressive initiative on any stalled projects, fearlessly pitch new, bold ideas, and firmly assert your leadership capabilities. Highly competitive opportunities arise now—you must embrace them with absolute confidence and a winner's mindset. Your highly proactive, relentless approach naturally attracts the positive attention of key decision-makers, investors, and potential high-level mentors.",
  4: "April continues the high-octane momentum with sustained, unyielding drive and focus. Your complete attention must shift to flawless execution rather than further planning or discussion. Your heightened physical energy perfectly supports demanding, grueling work schedules and navigating extremely tight, stressful deadlines. You must actively channel any brewing workplace tensions or competitive friction productively by staying hyper-focused solely on your deliverables and concrete, measurable results.",
  5: "May beautifully brings a much-needed sense of harmony, grace, and ease to your workplace dynamics. Highly creative collaborations, team bonding events, and social networking rapidly strengthen your overall professional position. Your client relationships flourish and expand significantly through your genuine, warm engagement and your highly refined, diplomatic communication style. Artistic, aesthetic, and major design-oriented projects gain particular, highly lucrative traction this month.",
  6: "June heavily favors deep analytical work, complex problem-solving, and communication-heavy, detailed tasks. Delivering major presentations, writing comprehensive reports, and engaging in high-stakes negotiations will produce exceptionally strong, profitable outcomes. Focusing on meticulous documentation and systemic process improvement will yield incredibly valuable efficiency gains for your team. Your absolute clarity of thought and articulate, persuasive expression become your major, undeniable professional advantages.",
  7: "July significantly heightens your emotional awareness and intuition in all professional settings. You must learn to implicitly trust your gut instincts and initial feelings when making complex, confusing career decisions. Public-facing roles, human resources, and all service-oriented work absolutely thrive and expand during this emotionally resonant month. Your highly empathetic, emotionally intelligent leadership style resonates deeply with both your colleagues and your most demanding clients.",
  8: "August powerfully spotlights your natural leadership abilities, massive personal confidence, and public visibility. You must aggressively take complete ownership of high-profile, risky projects and demonstrate your unique expertise loudly and confidently to the world. Formal recognition, awards, or promotions from senior management and key authority figures become highly likely and deserved. This is an absolutely excellent, prime month for aggressive performance reviews and demanding major career advancements.",
  9: "September sharply focuses your mind, dramatically increasing your analytical precision and research capabilities. Highly detailed, meticulous, and perfection-oriented work produces exceptional, flawless results that impress everyone. Enrolling in advanced training programs, acquiring new certifications, and engaging in serious skill upgrades are highly favored and necessary during this period. Your incredibly thorough, microscopic approach to solving complex problems earns you profound, lasting professional respect.",
  10: "October vastly strengthens your professional partnerships, business marriages, and strategic corporate alliances. Entering into joint ventures, signing major contracts, and launching collaborative initiatives bring massive, mutual financial benefits. Actively seeking a balance in your work-life dynamics actually improves your overall professional effectiveness and high-level creative output. Highly diplomatic, tactful negotiations reach extremely favorable, profitable, and harmonious conclusions for all parties.",
  11: "November rapidly and beautifully expands your professional horizons through higher learning, global exploration, and big-picture thinking. Excussive conferences, elite mentorship programs, and lucrative international business opportunities present themselves seemingly out of nowhere. Your enthusiastic willingness to embrace entirely new cultural perspectives and highly innovative philosophical approaches positions you perfectly for explosive, significant career growth and massive paradigm shifts.",
  12: "December is the ideal, quiet month for deep professional reflection, gratitude, and long-term strategic planning. You must carefully review your massive accomplishments and set the structural groundwork for the next, even bigger cycle. The profound wisdom you have gained through the entire year's intense experiences finally crystallizes into a crystal-clear career direction. Openly and generously express your gratitude to the mentors, bosses, and reliable collaborators who supported your incredible journey.",
};
