/**
 * Family Interpretation Blocks
 */

export const FAMILY_DASHA_BLOCKS = {
  saturn_active:
    "All family relationships will absolutely require an extraordinary amount of deep patience, stoic understanding, and mature responsibility during this demanding period. Your elders, aging parents, or senior family members may suddenly need significantly more of your direct care, time, and financial attention due to declining health or changing circumstances. Heavy, undeniable responsibilities toward your parents and older family members increase dramatically, often feeling like a heavy burden. However, this is a profoundly important karmic time for actively deepening your familial bonds through your consistent, reliable presence and offering rock-solid support, even when family situations feel incredibly challenging, restrictive, or emotionally draining. Taking your family duties seriously and honoring your ancestral roots bring immense, hidden spiritual rewards. You are learning to become the unshakeable, reliable bedrock upon which your entire extended family can safely lean during times of crisis.",
  jupiter_active:
    "Overall family harmony, domestic joy, and mutual understanding receive a massive, incredibly positive, and beautiful boost during this expansive period. Highly auspicious events, large family celebrations, joyous reunions, and positive, expansive developments within the extended family are extremely likely and frequent. The education, moral growth, and overall success of the children in your family absolutely flourish and expand under this highly beneficial, protective influence. Deep wisdom passed down from respected elders and spiritual mentors beautifully guides your major family decisions toward lasting prosperity and ethical alignment. Actively participating in shared spiritual practices, engaging in generous family philanthropy, or undertaking religious pilgrimages together significantly enhances your domestic peace, brings deep togetherness, and heals old familial wounds. Your home becomes a sanctuary of optimistic, expansive light and genuine love.",
  mars_active:
    "Your core family dynamics may frequently experience highly heightened, explosive tensions and sudden, fiery arguments. Serious property disputes, aggressive disagreements over inheritances, or intense, competitive conflicts with your siblings are highly possible and require careful mediation. You absolutely must actively and consciously channel this intense, combative energy into highly constructive, physical family activities—such as initiating major home renovations, aggressively improving your family's physical security, or fiercely standing up together to protect your shared family interests against outside threats. Exercising extreme patience, enforcing strict boundaries, and practicing highly controlled, non-reactionary communication are the only ways to successfully prevent unnecessary, damaging conflicts from tearing through the household. Focus your family's fiery energy outward toward achieving shared goals rather than fighting internally.",
  venus_active:
    "Profound domestic harmony, beautiful family celebrations, and a deep appreciation for your loved ones are powerfully and joyfully highlighted. Your intimate relationships with your spouse and all in-laws improve significantly and naturally through mutual appreciation, diplomatic communication, and genuine affection. Your physical home environment naturally becomes significantly more beautiful, aesthetically pleasing, and peaceful as you invest time and resources into interior decoration and creating comfort. Engaging actively in creative, artistic pursuits within the family, attending cultural events together, and simply enjoying luxurious meals bring massive, shared joy. Hosting elegant social gatherings, throwing warm dinner parties, and actively nurturing your extended family network significantly strengthen and elevate your family's overall social standing and deepest bonds.",
  mercury_active:
    "Clear, logical communication and intellectual exchange within the family improve significantly, resolving many past misunderstandings. Engaging in highly important, detailed family discussions, navigating complex legal matters together, and meticulously planning the educational future of the children produce exceptionally positive, successful outcomes. Your siblings, cousins, and younger relatives play a highly active, incredibly supportive role in your daily family affairs and business decisions. Engaging in shared intellectual activities, taking courses together, playing strategic games, and prioritizing lifelong learning experiences rapidly bring the family much closer together mentally. This is an absolutely excellent, ideal time for signing family contracts, writing wills, organizing family archives, or decisively clarifying any confusing, lingering family communication issues.",
  rahu_active:
    "Highly unconventional, surprising, or radically modern family dynamics may suddenly emerge and significantly challenge your traditional expectations. Cultivating absolute acceptance, extreme open-mindedness, and adapting to modern realities are strictly required to support and maintain your family's harmony. Actively embracing foreign connections, adopting children, or joyfully integrating non-traditional family structures bring incredibly unique, unexpected blessings and massive growth to your lineage. You must intelligently and diplomatically navigate heavy, outdated family expectations with modern wisdom, carefully honoring your ancestral traditions while simultaneously, aggressively embracing the progressive values that truly serve the family's future evolution. Do not let fear of societal judgment dictate how you structure or openly love your unique family.",
  ketu_active:
    "Quiet, deeply esoteric spiritual connections and unspoken intuitive bonds within your family deepen profoundly and mysteriously. Very old, deeply buried family secrets or unresolved ancestral issues may suddenly resurface demanding final healing, forgiveness, and complete karmic resolution. Invisible, powerful ancestral influences strongly guide your major family decisions toward achieving necessary karmic completion and spiritual liberation. Actively cultivating a profound sense of inner detachment from petty family drama and releasing toxic enmeshment paradoxically brings you a much deeper, clearer understanding and highly authentic, peaceful family relationships. You may feel physically distant from your family but spiritually closer than ever before. Healing the family trauma stops with you.",
  sun_active:
    "The strong influence of father figures, grandfathers, and deeply patriarchal traditions become highly prominent and deeply respected in your family life. Taking on absolute leadership, assuming final responsibility, and guiding the family structure falls completely and naturally to you right now. Your unwavering confidence, massive personal authority, and highly decisive nature perfectly guide the entire family safely and successfully through making incredibly important, high-stakes decisions. Benefiting from significant government grants, receiving elite institutional support, or gaining public recognition for your family's massive contributions becomes readily available and highly likely. You must proudly step into the role of the benevolent, protective sovereign of your household, leading completely by honorable example.",
  moon_active:
    "Deep maternal bonds, the nurturing influence of mothers, and profound, emotional family connections strengthen significantly and beautifully. Your physical home truly becomes an absolute sanctuary of deep comfort, safety, and endless nurturing for everyone who enters it. The complex emotional and psychological needs of the children take absolute top priority, and your highly intuitive, empathetic parenting style creates a deeply supportive, unshakable family environment. Hosting warm, intimate domestic celebrations, cooking large family meals, and prioritizing highly emotional family gatherings bring profound, tearful joy and a massive sense of total belonging. Your family is your most secure emotional anchor; invest your whole heart into them right now.",
};

export const FAMILY_HOUSE_BLOCKS = {
  jupiter_4th:
    "Incredible domestic happiness, absolute peace at home, and massive, expanding family prosperity are strongly and beautifully indicated. Undertaking major, luxurious home upgrades, making highly profitable real estate or property purchases, and actively creating an incredibly harmonious, spiritually rich living environment align perfectly with your current, expansive energies. The deeply loving, highly philosophical influence of your mother or a maternal figure brings immense, profound wisdom, psychological comfort, and undeniable blessings to the entire functioning household. Your home physically expands to accommodate more joy, more people, and significantly more abundance.",
  saturn_4th:
    "Heavy, unavoidable domestic responsibilities and strict household duties increase significantly, demanding your full attention. Undertaking major, necessary structural home repairs or improvements, providing intense elder care for sick parents, and fulfilling heavy family obligations require your incredibly dedicated, unwavering attention. Aggressively building a highly stable, completely secure home foundation through sheer patience, gruelling hard work, and incredibly consistent, daily effort creates lasting, impenetrable family security for generations. The home feels more like a place of serious duty and hard work right now than a place of lighthearted relaxation.",
  mars_4th:
    "Massive, aggressive energy is heavily directed toward major, rapid home improvement projects, intense property acquisitions, and aggressively fortifying your family's physical protection. Engaging in complex property-related legal activities, securing real estate deals, and heavily upgrading your home security systems become your absolute top priorities. You must fiercely, actively guard against sudden, explosive family arguments occurring directly within the home by consciously channeling your excess, aggressive energy into highly constructive, physically demanding domestic projects. Make sure the home remains a safe haven, not a battlefield.",
  venus_4th:
    "Extensive home beautification, highly luxurious interior design, and creating exceedingly comfortable, aesthetically pleasing living spaces receive your massive, joyful attention. Overall family harmony absolutely thrives through shared artistic expression, playing music in the home, and actively enjoying shared, high-end aesthetic experiences together. Consciously creating incredibly warm, deeply welcoming, and socially vibrant domestic environments significantly strengthens your deepest family bonds and attracts wonderful, supportive guests. Your home becomes a beautiful showcase of your elegant taste and your deep love for your family.",
  moon_4th:
    "Incredibly deep, unspoken emotional connections, profound empathy, and psychological understanding within the family bring immense comfort, healing, and unshakeable stability. Your naturally fierce nurturing instincts and highly protective nature create an incredibly warm, deeply safe, and emotionally secure home environment for all your loved ones. The physical health, emotional well-being, and overall happiness of your mother or a primary maternal figure highly deserve your absolute, special attention, deep care, and active devotion during this highly sensitive period. You feel most yourself when surrounded by the absolute safety of your inner family circle.",
};

export const FAMILY_PERSONAL_YEAR_BLOCKS: Record<number, string> = {
  1: "You are entering a powerful year of entirely new, exciting family beginnings—joyous births, beautiful marriages, or completely new, independence-seeking living arrangements bring massive excitement. Cultivating strong personal independence within your family relationships actually creates significantly healthier, more balanced dynamics for everyone. Boldly initiating massive, highly positive changes in outdated family patterns and bravely setting completely new, firm boundaries sets the absolute, perfect tone for harmony in the many years ahead. You must be the brave pioneer in leading your family toward a brighter, more honest future.",
  2: "Absolute family harmony is achieved completely and solely through deep cooperation, extreme diplomacy, and endless, patient compromise. Exercising massive patience with difficult family members and practicing highly attentive, empathetic listening radically strengthen your deepest familial bonds. Your core partnership within your marriage or deep, committed relationship deepens profoundly through practicing active mutual understanding, gentle communication, and the graceful, loving accommodation of each other's complex emotional needs. Peace at all costs should be your family motto this year.",
  3: "Expect a year filled to the brim with highly joyful family experiences achieved through massive social gatherings, huge, loud celebrations, and shared, highly creative activities. Your children's impressive academic or creative achievements bring you immense pride, deep happiness, and public recognition. Open, joyful family communication absolutely flourishes, and engaging in shared, highly expressive creative projects flawlessly unites all family members in deeply meaningful, unforgettable ways. Laughter and artistic expression are the best medicines for any lingering family woes right now.",
  4: "Your primary focus must be on aggressively building unshakeable family stability entirely through highly practical, boring, but necessary measures—such as executing major structural home improvements, rigorous family financial planning, and establishing strict, highly predictable daily family routines. The immense, exhausting hard work you purposefully invest into creating these incredibly solid, immovable family foundations directly supports and protects your lineage for generations to come. Discipline your children with love, manage your household budget flawlessly, and prioritize unshakeable family security.",
  5: "Your core family dynamics will inevitably experience massive, highly exciting, and somewhat chaotic changes—sudden relocations, extensive international travel, or wonderfully welcoming entirely new family members. Maintaining extreme emotional flexibility and an enthusiastic openness to radical change actively help everyone adapt quickly and joyfully. Bravely and permanently breaking highly outdated, toxic family patterns rapidly creates the necessary psychological space for vastly healthier, much more authentic, and deeply liberating relationships to finally blossom.",
  6: "Taking on intense family responsibilities, deep nurturing, and serious caregiving become the absolute, central, undeniable themes of your entire year. Actively creating a deeply loving, meticulously clean, and highly nurturing home environment is profoundly and soulfully fulfilling for you. Your endless, selfless willingness to happily serve your family's complex daily needs massively strengthens your core bonds and beautifuly creates a lasting, unforgettable legacy of pure love and unshakeable support. Your home is your absolute castle, and your family is your greatest, most cherished treasure.",
  7: "Deeply quiet family time, enforced solitude, and highly introspective, meaningful conversations profoundly deepen the psychological understanding between all family members. Engaging in shared, esoteric spiritual practices or deep meditation within the family unit brings immense, unshakeable peace and absolute cosmic alignment. Actively seeking out professional family therapy or psychological counseling for addressing deep, old family issues yields incredibly transformative, highly necessary insights and permanent healing.",
  8: "The overarching family's financial security, total material well-being, and social status improve massively through your highly smart, strategic decisions and highly assertive, confident action. Major family property investments, large real estate purchases, and shared family business ventures prosper incredibly and undeniably. Your absolute, undeniable leadership and total executive control in all serious family financial matters create massive, lasting prosperity and unshakeable material security for your entire lineage.",
  9: "This marks the profound completion of massive, nine-year family cycles—celebrating significant graduations, major retirements, or finally, permanently settling long-standing, divisive family matters. Practicing absolute, unconditional forgiveness of deep, past familial wounds brings profound, systemic healing to your entire bloodline. Actively preparing the entire family for the massive new chapters and fresh starts ahead beautifully creates a deep sense of highly peaceful, much-needed closure and loving unity.",
};

export const FAMILY_MONTHLY_BLOCKS: Record<number, string> = {
  1: "January powerfully and definitively sets the overarching, serious tone for all family dynamics throughout the entire year. Engaging in highly structured family goal-setting, meticulously planning new family traditions, and deeply reconnecting after the chaotic holidays massively strengthen your core bonds. You must openly discuss the family's largest, most ambitious aspirations and actively create shared, measurable objectives that perfectly align everyone's intentions, ensuring total family unity for the challenging months ahead.",
  2: "February vastly and beautifully enhances the deep, emotional connections within the entire family unit. Focusing heavily on Valentine's Day and dedicating massive time to partnership-focused, highly romantic activities massively strengthen your core marital or long-term partner bonds. Exercising extreme patience and demonstrating profound, empathetic understanding with difficult family members beautifully creates a highly supportive environment where absolutely everyone feels deeply valued, truly heard, and completely emotionally secure.",
  3: "March rapidly brings highly active, fiery, and slightly competitive family energy into the household. Initiating heavily active outdoor family adventures, starting massive spring cleaning projects, and totally refreshing the home's interior deeply invigorate your overall household dynamics. You must address any lingering, toxic family tensions completely directly but incredibly compassionately before they explode. Your highly proactive, take-charge approach to aggressively maintaining family harmony creates massive, positive momentum.",
  4: "April crucially sustains the massive, energized family interactions and intense physical activity from last month. Engaging heavily in competitive family sports, going on massive outdoor adventures, and initiating highly physical, competitive activities build incredible togetherness and teamwork. You must fiercely guard against sudden, explosive family arguments by consciously channeling this massive collective energy exclusively into highly fun, physically exhausting, shared experiences that bond rather than divide.",
  5: "May beautifully and softly brings absolute aesthetic beauty, deep peace, and profound harmony directly to the home environment. Hosting large, beautiful family celebrations, investing in high-end home decoration, and attending shared cultural activities massively enrich your domestic life. All romantic partnerships within the core family benefit immensely from highly thoughtful, romantic gestures, carving out extensive quality time, and offering genuine, highly physical expressions of pure affection.",
  6: "June heavily and explicitly favors clear family communication, logic, and engaging heavily in shared educational activities. Dedicating massive time to helping children with complex academics, highly organizing logistical family trips, and having deep, intellectual discussions bring the family significantly closer. All sibling relationships benefit immensely from practicing brutally open dialogue, initiating intellectual debates, and offering massive mutual support during this highly mentally active, communicative month.",
  7: "July profoundly and beautifully deepens all emotional, unspoken family bonds and psychological connections. You must actively create highly nurturing, emotionally resonant family rituals—such as sharing all evening meals without screens, engaging in deep storytelling, and establishing highly comforting bedtime routines. The children in your family especially benefit massively from your total, undivided emotional attentiveness and physical presence. Family traditions centered entirely around the safety of the home and hearth bring lasting, beautiful memories.",
  8: "August brightly and powerfully highlights your absolute family leadership and your undeniable, respected parental authority. You must aggressively make all highly important, high-stakes family decisions with absolute confidence and sovereignty, while still respectfully listening to each member's voice. Immense family pride and celebrating major shared achievements bring explosive, public joy. Extravagantly celebrate all family milestones and proactively reinforce the family's collective identity, pride, and shared, ambitious purpose.",
  9: "September brings the absolute necessity for highly organized, meticulous, and strict family planning. Establishing rigid back-to-school routines, scheduling comprehensive annual health screenings, and strictly enforcing highly structured, daily family schedules create immense, much-needed stability. Your highly detailed, almost microscopic attention to every single family member's exact daily needs flawlessly demonstrates your profound care and perfectly creates an incredibly well-functioning, highly efficient household environment.",
  10: "October actively forces you to perfectly balance all complex family relationships entirely through absolute fairness and high-level diplomacy. You must expertly resolve any lingering family disputes with total equanimity, playing the ultimate peacekeeper, and ensuring you listen fully and impartially to all perspectives. Attending major family social events and engaging heavily in local community involvement vastly strengthen your family's overall social position, public reputation, and deep sense of local belonging.",
  11: "November rapidly and beautifully expands your family's overarching horizons through planning massive international travel, engaging in deep cultural exploration, and enthusiastically learning entirely new subjects together. Sharing deep ancestral family wisdom traditions and engaging heavily in massive, joyful holiday preparations bring incredible, undeniable warmth and profound connection. Practicing immense, unconditional generosity both within and completely beyond your immediate family circle creates absolutely abundant, karmic blessings for everyone.",
  12: "December beautifully, soulfully celebrates total family unity, immense peace, and deep, quiet reflection. Fully engaging in all cherished holiday traditions, hosting massive, joyous family gatherings, and openly expressing profound, tearful year-end gratitude massively strengthen the unshakeable family bond. Take quiet time to deeply reflect on the entire family's massive growth and challenges throughout the year, and set highly loving, united intentions for the beautiful shared journey ahead.",
};
