/**
 * Finance Interpretation Blocks
 */

export const FINANCE_DASHA_BLOCKS = {
  saturn_active:
    "Extreme financial discipline and an unwavering commitment to a strict budget are absolutely paramount during this extended period. This is not the time to take financial risks, chase get-rich-quick schemes, or engage in highly speculative investments, as Saturn severely punishes financial recklessness. Your complete focus must shift entirely toward steady, reliable, long-term wealth building and the meticulous preservation of your capital. Traditional savings plans, fixed term deposits, government bonds, and highly conservative, low-yield but guaranteed investment strategies will ultimately yield the absolute best, most secure returns for you right now. Patience with money matters is completely non-negotiable; you must understand that true financial security is built brick by brick over time, rather than through fleeting, lucky gains. Building a robust emergency fund and aggressively paying down high-interest debt must be your absolute top priorities to ensure lasting peace of mind. The financial foundations you painstakingly lay during this period will protect you for the rest of your life.",
  jupiter_active:
    "A massive period of financial expansion, abundance, and greatly increased earning potential is strongly supported by wise, ethical decisions and well-researched investments. Highly lucrative opportunities for significant wealth growth through higher education, spiritual ventures, teaching, publishing, or high-level advisory roles will appear naturally and surprisingly in your life. Unconditional generosity in your charitable giving and a genuine willingness to share your abundance actually act as powerful magnets, bringing massive, unexpected financial returns back to you, often from entirely unforeseen sources. Financial decisions that are deeply guided by your core moral principles and a desire to uplift others will create highly sustainable, generational prosperity. This is an absolutely excellent, golden time to confidently ask for an raise, expand your business operations, or seek major funding for your large-scale projects, as the universe is highly responsive to your financial ambitions right now.",
  mars_active:
    "Your raw financial energy and burning desire for immense wealth accumulation run extremely high right now—you must consciously and aggressively channel this intense drive constructively. Massive investments in real estate, launching highly competitive business ventures, and taking bold, calculated risks in the stock market may pay off handsomely, provided you have done your due diligence. However, you must actively and forcefully avoid impulsive, emotionally driven spending or engaging in dangerous, blind financial speculation, as Mars can burn through money just as quickly as it earns it. Your fierce assertiveness, unwavering confidence, and demanding nature in hardcore financial negotiations can easily secure you significantly better deals, higher salaries, and highly favorable terms across all your contracts. You must heavily rely on strategic, tactical financial planning rather than just brute-force earning to ensure that your rapid gains are actually preserved.",
  venus_active:
    "A strong, almost irresistible desire for extreme luxury, unparalleled comfort, and beautiful surroundings highly attracts significant spending during this pleasant period. While it is absolutely fine and encouraged to enjoy life's finest pleasures and reward yourself for your hard work, you must actively maintain a strict, overarching financial balance to prevent draining your resources. Highly profitable investments in fine art, the beauty industry, high-end fashion, luxury hospitality, or any creative, aesthetically driven industries may prove incredibly lucrative for you right now. Entering into harmonious, legally sound financial partnerships, joint ventures, and wisely managing shared resources with your spouse or business partners bring massive, mutual financial benefits when approached with maximum grace and absolute transparency. Your ability to charm and socialize directly correlates to an increase in your overall, lucrative earning opportunities.",
  mercury_active:
    "Deploying sharp, highly analytical financial planning, logic, and cold, hard data analysis will yield exceptionally excellent, profitable results for you. This is the absolute ideal, perfect time for meticulously reviewing your entire investment portfolio line by line, aggressively renegotiating existing business contracts, and actively exploring the creation of multiple, diverse income streams. Increasing your overall financial literacy, studying market trends, and making highly informed, logic-based financial decisions are your absolute strongest, most reliable wealth-building tools during this intellectually active cycle. Be sure to meticulously read the fine print on any financial documents before signing, as your attention to detail will directly save or make you substantial amounts of money. Careers or side-hustles heavily involving writing, coding, mass communication, or high-volume sales will prove particularly, surprisingly profitable.",
  rahu_active:
    "Highly unusual, surprisingly modern, and completely unexpected financial opportunities may suddenly present themselves, seemingly out of thin air. You must exercise extreme, almost paranoid caution and thorough due diligence with bizarre or highly unconventional investments, while simultaneously staying open-minded to radically innovative, highly disruptive wealth-building approaches. Cutting-edge technology-related investments, volatile cryptocurrencies, and massive international financial opportunities deserve your very careful, objective evaluation, as they hold the potential for massive gains or equally massive losses. You may experience sudden, shocking windfalls followed by confusing expenses; maintaining a rock-solid, traditional emergency fund is absolutely critical to navigating this highly erratic, unpredictable financial energy safely. Do not let greed or the Fear Of Missing Out (FOMO) dictate your long-term financial strategy.",
  ketu_active:
    "Your psychological and emotional attachment to strict material wealth and traditional financial goals completely loosens, which paradoxically, and surprisingly, may bring profound, unexpected financial gains into your life. You will find that deep spiritual investments, generous charitable giving, or funding altruistic projects satisfy your soul significantly more deeply than the relentless, empty accumulation of personal material wealth. Past, long-standing financial problems, confusing debts, or tricky inheritance issues may completely resolve themselves during this time, permanently clearing the path for an entirely fresh, unburdened financial outlook. You are rapidly learning the ultimate, profound truth that true, lasting wealth is an internal state of abundant being, entirely separate from the volatile, ever-changing numbers in your bank account. Trust that the universe will always provide exactly what you need, exactly when you need it.",
  sun_active:
    "Highly profitable, secure government-related income, assuming major authority positions, and receiving massive leadership bonuses are strongly and brightly highlighted for you right now. Your overall public reputation, personal brand, and the respect you command in your industry directly, immediately, and measurably impact your total earning potential. Conservative, powerful investments in physical gold, highly precious metals, blue-chip stocks, and major government bonds see exceptionally favorable, highly stable conditions during this bright, powerful period. You must confidently step into the financial center stage, boldly demand exactly what your elite expertise is worth, and refuse to settle for anything less than top-tier compensation. Financial independence and achieving absolute sovereignty over your vast resources are your ultimate, achievable goals right now.",
  moon_active:
    "Your day-to-day financial fluctuations will deeply, accurately mirror your internal, cyclical emotional states—you must become highly aware of this connection. To combat this, you must actively maintain strict financial stability by implementing fully automated, robotic savings plans and relying heavily on rigid, pre-planned, mathematical budgets to prevent emotional overspending. Highly lucrative investments in residential real estate near large bodies of water, the thriving hospitality sector, the food industry, and deeply nurturing, caretaking businesses benefit massively from the current, fluid lunar financial energy. You must consciously prioritize building intense, profound feelings of absolute financial security and emotional safety over chasing highly risky, volatile, stress-inducing investments. Always trust your deep, immediate gut intuition when making crucial choices regarding major, life-altering financial investments.",
};

export const FINANCE_HOUSE_BLOCKS = {
  jupiter_2nd:
    "There are exceptionally strong, overwhelmingly positive indicators for massive, long-term wealth accumulation and highly significant, consistent income growth. Extensive family wealth, massive inheritances, or gaining control of lucrative shared assets may contribute enormously and surprisingly to your overall net worth. Your deeply values-driven, highly ethical approach to strict money management naturally creates profound, sustainable prosperity that perfectly aligns with your highest life principles. You have an almost magical, Midas-touch ability to rapidly grow your financial resources through sheer optimism, unshakeable faith, and continuously making highly principled, fundamentally sound financial decisions.",
  saturn_2nd:
    "Severe, restrictive financial constraints or temporary periods of frustrating scarcity will violently teach you incredibly valuable, life-altering lessons about strict money management. Although immensely delayed, highly substantial and massive financial returns will ultimately, richly reward the incredibly patient, unshakeable investor willing to play the long game. Aggressively building massive, untouchable emergency funds and ruthlessly reducing all high-interest debt must be absolutely prioritized over any form of frivolous luxury spending during this highly restrictive, demanding period. You are slowly, painfully, but surely building an incredibly solid, completely impenetrable financial fortress that will protect your family for generations to come.",
  venus_2nd:
    "A highly comfortable, deeply luxurious, and abundant financial position strongly supports your total enjoyment of life's finest, most expensive pleasures without guilt. Your overall income through highly creative work, the beauty industry, and all artistic or aesthetic endeavors increases significantly, easily, and naturally. A perfect, delicate balance between strategic saving and joyful spending perfectly maintains your overall financial harmony, while still allowing you to fully enjoy the rich, sweet fruits of your considerable labor. You possess a completely natural, effortless talent for attracting significant money, lucrative resources, and beautiful, highly valuable possessions into your life entirely through your innate charm and grace.",
  mars_2nd:
    "Highly aggressive, fast-paced financial strategies may certainly bring incredibly quick, massive gains, but they absolutely also carry an exponentially higher, potentially devastating risk of sudden loss. You must purposely channel your intense competitive energy exclusively into highly calculated entrepreneurial ventures with excellent, thoroughly researched risk-reward ratios. You must forcefully, actively avoid making large, impulsive purchases driven entirely by sudden emotional reactions, petty competition, or a temporary desire to aggressively show off your wealth to others. Your sheer, unstoppable drive to rapidly accumulate massive wealth is incredibly powerful, but it urgently requires strict, cold discipline to be truly, sustainably effective.",
  rahu_11th:
    "Massive, shockingly large financial gains obtained through highly unconventional, incredibly modern, or strictly foreign sources are highly and distinctly possible for you. Massive, active expansion of your global, elite network directly and immediately brings incredibly lucrative, unexpected financial opportunities directly to your doorstep. Aggressive investments in bleeding-edge technology, artificial intelligence, and radically innovative, disruptive business models create powerful, fast pathways to highly significant, sudden wealth accumulation. You possess a unique, powerful, almost visionary flair for instantly spotting massive, highly lucrative financial trends long before the general public or traditional markets ever catch on.",
  jupiter_11th:
    "Massive financial gains, the sudden realization of huge profits, and the complete fulfillment of your deepest material desires are strongly and beautifully indicated. Your extensive, elite social connections and active participation in high-level group networks bring you massive, highly lucrative, and effortless financial opportunities. Engaging in major philanthropy, charitable giving, and highly ethical, socially responsible investing creates a massive, positive karmic cycle of endless abundance and deeply purposeful, soul-satisfying wealth creation. Your ultimate financial success is deeply, inextricably linked to your genuine ability to generously uplift, support, and financially enrich your wider community.",
};

export const FINANCE_SIGN_BLOCKS = {
  jupiter_sagittarius:
    "You possess an incredibly optimistic, limitlessly expansive financial outlook, expecting massive growth through international foreign trade, higher education, or global publishing. Your deeply philosophical, highly ethical approach to generating wealth heavily emphasizes continuous growth through acquiring knowledge and maintaining the highest standards of ethical business practices. Wealth flows to you naturally when you think globally rather than locally.",
  venus_taurus:
    "You are strongly destined for immense material security, acquiring highly valuable tangible assets, and enjoying wonderfully steady, virtually guaranteed income growth. Major investments in commercial real estate, luxury goods, fine art, and all high-quality, tangible assets perform exceptionally well for you over time. Your highly practical, grounded, and patient approach to strict money management slowly builds an empire of lasting wealth.",
  saturn_capricorn:
    "Incredibly disciplined, emotionally detached financial management uniquely creates massive, impenetrable long-term wealth for you. Adhering to highly conservative, mathematically proven investment strategies and focusing exclusively on career-focused income growth ensure incredibly stable financial foundations that perfectly support your highest, most ambitious corporate goals. You view money strictly as a tool for power and security, not for frivolous fun.",
  mercury_virgo:
    "Your incredibly sharp, highly analytical, and completely unsentimental financial planning absolutely excels above all others. Meticulously detailed, spreadsheet-driven budgeting, continuous portfolio optimization, and relentlessly cost-effective business strategies maximize your total financial returns. Your incredibly thorough, microscopic approach to money management effectively prevents any wasteful spending and ensures maximum, optimal efficiency across all your accounts.",
};

export const FINANCE_PERSONAL_YEAR_BLOCKS: Record<number, string> = {
  1: "This marks a year of incredibly fresh, highly potent financial beginnings and aggressive new initiatives. You must immediately start aggressive new savings plans, actively explore completely new, innovative income streams, and heavily invest in personal skill growth that directly and exponentially increases your core earning potential. Bold, massive financial moves, such as starting a new business or making a major investment, are highly favored, provided they are backed by incredibly solid, meticulous planning and exhaustive market research. You must take complete, absolute charge of your ultimate financial destiny right now; rely completely on your own initiative rather than waiting for others to provide for you.",
  2: "This is a year strictly designated for highly patient, frustratingly steady, but ultimately extremely secure financial progress. You must absolutely avoid taking any major, speculative financial risks or making impulsive, large purchases. Your complete focus must be on harmoniously sharing resources with your legal partners and actively building impenetrable, joint financial security. Highly cooperative financial ventures, joint bank accounts, and carefully planned shared business investments vastly strengthen your overall wealth position. Patience and extreme attention to all financial details are your greatest, most reliable assets this year.",
  3: "Your overall spending on highly enjoyable social activities, entertainment, and creative, artistic pursuits will sharply and undeniably increase this year. You must actively work to balance this intense enjoyment of life with a bedrock of strict savings discipline. Your core income generated through creative expression, massive communication, writing, and intensive social networking grows significantly and easily. It is highly advised to strategically invest your money in high-quality experiences, travel, and events that actively, measurably expand your influential professional network.",
  4: "You must budget incredibly carefully and heavily invest your capital exclusively in highly stable, tangible, long-term assets. This is the ultimate foundational building year for securing your lifelong financial security—you must aggressively focus on violently reducing all debt, massively increasing your emergency savings, and establishing incredibly solid, unbreakable financial systems. The intense, boring financial discipline and strict budgeting you aggressively exercise right now will pay massive, exponential dividends for many years to come.",
  5: "Massive, unpredictable financial changes and sudden, highly unexpected expenses are incredibly likely to occur this year. You must absolutely maintain a massive, fully funded liquid emergency fund while remaining highly open, agile, and alert to completely new, bizarre earning opportunities. Ultimate financial adaptability is absolutely crucial right now—developing multiple, diverse income streams provides the only true, reliable security during these inevitable periods of extreme financial volatility and rapid market disruption.",
  6: "Massive, largely unavoidable family-related expenses, domestic needs, and obligations are highly prominent and demanding this year. Major home improvements, purchasing real estate, and heavily investing in the ultimate security of your family are highly worthwhile and ultimately profitable endeavors. Your deeply responsible, loving approach to handling heavy financial obligations vastly strengthens your core family bonds and successfully creates an incredibly stable, unshakeable domestic foundation that supports all your future ambitions.",
  7: "This represents a deeply reflective, quiet, and highly analytical period for all your finances. You must intensely study complex investment strategies, actively seek out elite expert advice, and absolutely avoid making any major, binding financial commitments until absolute, crystal clarity arrives. Deep, psychological analysis of your lifelong financial patterns, subconscious spending habits, and deep-seated fears regarding money reveals massive, hidden opportunities for optimization, healing, and exponential growth.",
  8: "You have finally reached the ultimate, absolute peak of your financial potential for this entire nine-year cycle. Massive business expansion, highly lucrative commercial property deals, and massive career advancement bring you enormous, undeniable material rewards and cash flow. Your highly strategic, cold approach to massive wealth creation yields incredibly significant, life-altering returns. You must unapologetically assert yourself in all high-stakes financial negotiations and aggressively demand the absolute highest terms in all your business dealings.",
  9: "Unconditional generosity, massive charitable giving, and clearing out old debts ultimately enrich you far more than hoarding wealth. Making significant charitable contributions brings you highly unexpected, almost magical financial returns from the universe. You must completely finalize and close out all outstanding, lingering financial obligations, pay off old debts, and mentally prepare for the entirely fresh, new financial cycle ahead. Fully releasing your tight, anxious attachment to specific material outcomes paradoxically attracts massive, flowing abundance into your life.",
};

export const FINANCE_MONTHLY_BLOCKS: Record<number, string> = {
  1: "January is the absolute ideal, mandatory time for rigidly setting your major annual financial goals and exhaustively reviewing your entire combined investment portfolios. Implementing strict budget planning, utilizing expense tracking apps, and aggressively cutting unnecessary subscriptions establish an incredibly strong, unshakeable financial foundation for the entire year. You must start the year with absolute, crystal clarity about your precise earning targets, your aggressive saving objectives, and your overarching financial reality.",
  2: "February deeply favors highly collaborative financial ventures, entering into joint business agreements, and managing shared investments with legal partners. Your overall partnership-based income grows significantly through building mutual trust and honoring deep, shared commitments. Exercising extreme patience with any slower-than-expected financial returns during this frustrating month perfectly positions you for a period of massively accelerated, exponential growth later in the year. Do not force financial matters right now.",
  3: "March brings incredibly active, fiery, and highly aggressive financial energy into your life. Bold, decisive investment decisions, launching completely new side-hustles, and actively initiating new income streams gain massive, undeniable traction. Major investments in commercial real estate, the energy sector, or physical commodities show particular, highly lucrative promise right now. Your highly decisive, fearless approach to seizing fleeting financial opportunities creates immediate, measurable, and highly profitable results.",
  4: "April crucially sustains the previous month's financial momentum through highly disciplined, meticulous execution. You must actively, aggressively monitor your investments daily and immediately adjust your overarching strategies based strictly on harsh quarterly performance metrics. Navigating a highly competitive business environment requires your absolute sharpest financial acumen, cold logic, and a highly strategic, almost military-like approach to your overall resource allocation and spending.",
  5: "May beautifully brings profound financial harmony through achieving a perfect, delicate balance between highly enjoyable spending and rigorous saving. Completely new, creative income streams and monetizing your artistic ventures show surprising, massive profitability. All partnership finances benefit immensely from brutally open, honest communication and fully aligning your long-term, shared financial goals. High-end luxury purchases, if researched and made wisely, will easily retain or even vastly increase their underlying value over time.",
  6: "June absolutely excels for deep, complex financial analysis, high-stakes deal-making, and signing contracts. Tough contract negotiations, aggressive salary discussions, and pitching massive business proposals will produce exceptionally favorable, highly lucrative outcomes for you. Significant, calculated investments in the technology sector, communication platforms, and software yield exceptionally strong, market-beating returns. You must meticulously document every single financial decision and keep flawless, audited records.",
  7: "July strictly requires absolute, iron-clad emotional discipline in all your financial matters. You must forcefully, consciously avoid making any massive, impulse purchases driven entirely by sudden mood fluctuations, anxiety, or emotional desires. Keeping robust savings strictly in easily accessible liquid assets provides the ultimate, necessary emotional security you crave right now. Making significant real estate investments near beautiful, natural water bodies or investing heavily in industries deeply connected to nurture, food, and care perform exceptionally well.",
  8: "August brightly and powerfully highlights massive income generation achieved directly through assuming high-level leadership and holding major authoritative positions. Aggressive salary negotiations, demanding massive performance bonuses, and seeking major promotions are perfectly timed, justified, and highly likely to succeed. Safe, reliable investments in physical gold, precious metals, and luxury brands attract incredibly stable, high-yield returns. The widespread public recognition of your elite work translates instantly and directly into massive financial advancement.",
  9: "September heavily favors incredibly detailed, practically microscopic financial planning and cold, hard data analysis. Engaging in aggressive tax planning, completely rebalancing your entire portfolio, and thoroughly reviewing all your expensive insurance policies are highly productive and immensely cost-saving tasks. Significant, long-term investments in higher education, advanced certifications, and rigorous skill development show incredibly strong, undeniable long-term financial returns that are absolutely worth aggressively pursuing now.",
  10: "October brings highly necessary financial balance directly through forming strong partnerships and engaging in highly cooperative, mutual business ventures. Major joint investments, sharing resources, and launching shared business ventures produce incredibly harmonious, mutually profitable returns. Enforcing a strictly balanced, highly logical approach to severe risk management ensures incredibly stable, consistent financial progress throughout the entire month. Diplomatic negotiations yield the absolute best, highest-paying financial results for everyone involved.",
  11: "November rapidly and beautifully expands your overarching financial horizons through utilizing deep, philosophical wisdom-guided investments. Massive international trade, launching global educational ventures, and prioritizing highly ethically aligned, socially responsible investments absolutely thrive and bring in massive profits. Your deeply generous, unconditionally giving approach to all your financial dealings mysteriously but powerfully attracts incredible, reciprocal prosperity and massive, meaningful business opportunities.",
  12: "December strongly calls for deep, silent financial reflection, expressing profound gratitude, and closing out the books. Conducting rigorous year-end financial reviews, engaging in massive, tax-deductible charitable giving, and laying out strategic, detailed planning for the new year create a massively positive, unstoppable financial cycle. You must permanently close the year with a completely clear, realistic, and brutally honest understanding of your exact financial position and your precise, aggressive future direction.",
};
