/**
 * Health Interpretation Blocks
 */

export const HEALTH_DASHA_BLOCKS = {
  saturn_active:
    "Your overall health and vitality now require incredibly consistent, unwavering attention to your daily lifestyle habits. Chronic conditions, specifically relating to joint pain, arthritis, bone density, and dental health, need close, regular medical monitoring. Implementing strict, regular exercise routines that focus on flexibility and strength training, ensuring adequate calcium and mineral intake, and practicing forced stress management through meditation become absolutely essential for your well-being. You must actively avoid overwork and physical exhaustion during this demanding period, as Saturn severely punishes those who ignore their body's inherent limits. Committing to a highly disciplined, boring but effective health routine will literally add years to your life and prevent mobility issues later. This is a time of slow, steady physical maintenance rather than pushing for athletic peak performance.",
  jupiter_active:
    "Your overall physical vitality and immune system receive a massive, highly positive boost during this expansive period. You generally feel a profound sense of physical well-being and abundant energy. However, you must actively watch for rapid, unwanted weight gain, elevated blood sugar, and potential liver-related issues arising directly from overindulgence in rich foods or alcohol. Adopting a highly balanced, moderate diet rich in whole grains, fresh vegetables, and lean proteins is absolutely crucial to intimately support your optimal health. Engaging deeply in spiritual practices, yoga, and spending time in nature massively enhance both your physical and mental well-being during this fortunate, benefic period. Healing from past ailments often occurs rapidly and almost miraculously under this highly protective influence. Keep your body moving to offset the tendency toward lethargy.",
  mars_active:
    "Incredibly high, surging physical energy levels powerfully support all strenuous physical activity, demanding athletic pursuits, and manual labor. However, you must actively and aggressively guard against sudden, acute accidents, severe inflammation, muscular tears, athletic injuries, and heat-related conditions. You must consciously channel this excess, fiery energy through grueling, regular exercise, martial arts, heavy weightlifting, or highly competitive sports to prevent it from manifesting as physical or mental agitation. Maintaining adequate, constant hydration and consuming cooling, alkaline foods are absolutely essential to balance Mars's intense, fiery influence on your constitution. If you feel sudden bursts of anger or frustration, use physical exertion as your primary release mechanism to maintain excellent health.",
  venus_active:
    "Issues surrounding reproductive health, hormonal balance, kidney function, and complex skin conditions may urgently need your holistic attention. Investing in high-quality beauty treatments, luxurious spa days, and dedicated, lengthy self-care routines become highly important for maintaining your overall physical and mental equilibrium. Maintaining deeply balanced nutrition, prioritizing a minimum of eight hours of adequate, high-quality sleep, and engaging in stress-reducing, pleasant activities powerfully support your natural, resilient vitality. You must actively and consciously avoid consuming excessive, refined sugars, binge drinking, and falling into highly indulgent, lazy eating patterns that will quickly compromise your immune system. Finding joy, pleasure, and deep satisfaction in your physical body is the ultimate key to unlocking your vibrant health right now.",
  mercury_active:
    "Your delicate mental health and nervous system absolutely must take the highest priority over everything else right now. Severe nervous tension, chronic anxiety, insomnia, and the physical exhaustion caused by constant overthinking may quickly surface and drain your vitality. Practicing daily mindfulness meditation, deep breathing exercises, and taking strict, enforced regular breaks from all digital screen time are vital to help maintain your mental clarity and prevent total burnout. Furthermore, your exact digestive health is incredibly sensitive to your stress levels; it benefits massively from maintaining highly regular, predictable meal times and consuming easily digestible, fiber-rich foods. Your mind and your gut are inextricably linked during this cycle; healing one automatically heals the other.",
  rahu_active:
    "Highly unusual, sudden, or frustratingly hard-to-diagnose health issues and phantom symptoms may frequently arise during this unpredictable period. You absolutely must seek out proper, comprehensive medical evaluation and multiple expert opinions for any persistent, strange symptoms rather than ignoring them. You must strictly avoid dangerous self-medication, relying on internet diagnoses, and experimenting with unproven alternative remedies without highly qualified, professional medical guidance. Maintaining strict mental health awareness, grounding yourself through physical touch, and actively making toxin-free, incredibly clean lifestyle choices heavily protect your overall, highly sensitive well-being. Beware of developing extreme hypochondria or bizarre phobias regarding your health; focus strictly on measurable, objective medical facts.",
  ketu_active:
    "Deep, esoteric spiritual health practices and alternative healing modalities become profoundly, almost miraculously healing for your physical body right now. Engaging deeply in classical Yoga, Vipassana meditation, and advanced pranayama (breathwork) offer incredible therapeutic benefits that extend far beyond mere physical fitness or flexibility. Strangely, very old, past health issues or childhood ailments may briefly resurface for final, karmic resolution and complete healing. Maintaining a state of intense, mindful awareness of your body's most subtle, quiet signals accurately guides you toward the optimal health practices and dietary changes you desperately need. Conventional medicine may fail to diagnose mysterious ailments that are rooted purely in energetic blockages or long-held spiritual trauma during this unique cycle.",
  sun_active:
    "Your baseline constitutional strength, physical radiance, and core vitality are powerfully highlighted and naturally robust right now. However, you must pay very close, specialized attention to maintaining excellent eye health, actively monitoring all heart conditions, and fiercely protecting yourself from severe, sun-related skin damage. Engaging in regular, rigorous cardiovascular exercise, scheduling comprehensive, annual eye checkups, and ensuring adequate, safe Vitamin D intake massively support your overall, radiant health during this highly solar-influenced period. Issues related to the spine, upper back, and overall posture also require your conscious, daily attention to prevent chronic pain. Your physical health is deeply tied to your sense of personal pride and how brightly you allow yourself to shine in the world.",
  moon_active:
    "Your highly fluctuating emotional health and psychological state directly, immediately, and profoundly impact your overall physical well-being. Issues such as severe water retention, intense hormonal fluctuations, digestive sensitivity, and highly erratic sleep quality genuinely need close, daily monitoring. Establishing incredibly calming, rigid routines before bedtime, drinking soothing herbal teas, and engaging in profound emotional self-care practices strictly maintain your physical and psychological equilibrium. You must stay incredibly well-hydrated with pure water and prioritize getting deep, restful, uninterrupted sleep above almost all other activities. Your physical body is acting as a highly sensitive, emotional sponge right now; protect your energy fiercely from toxic environments and negative people.",
};

export const HEALTH_HOUSE_BLOCKS = {
  saturn_6th:
    "Your day-to-day physical health and managing your daily routines become heavily central, unavoidable focus areas in your life. Any chronic, lingering conditions require incredibly diligent, highly disciplined management through strictly enforced, daily routines and ongoing, professional medical guidance. Implementing rigorous preventive healthcare measures, maintaining an impeccable diet, and scheduling highly regular, comprehensive medical check-ups absolutely prevent minor, annoying issues from rapidly escalating into major, debilitating medical concerns. Discipline is your absolute best medicine.",
  mars_6th:
    "Incredible, boundless physical energy powerfully supports your highly active, aggressive health management strategies. Engaging heavily in highly competitive sports, heavy weightlifting, and extremely vigorous exercise perfectly channels your massive excess energy positively. However, you must fiercely guard against acute injuries, cuts, burns, or muscular tears during these intense physical activities. Managing anger and workplace stress through physical exertion is vital. A ferociously strong, almost bulletproof immune system richly rewards your highly active, demanding lifestyle.",
  jupiter_6th:
    "You possess an incredibly positive, resilient health outlook completely fortified with powerful, natural healing abilities that often baffle doctors. However, you must closely and constantly monitor for sudden weight gain, fatty liver issues, and sluggish digestive health caused by a love of rich foods. Your inherently optimistic, upbeat attitude toward any health challenges genuinely accelerates your physical recovery times. Maintaining strict nutritional awareness, practicing portion control, and engaging in moderate, daily cardiovascular exercise perfectly maintain your delicate well-being balance.",
  saturn_1st:
    "Your fundamental physical constitution and bodily structure face ongoing, grinding tests that ultimately build incredible, lifelong physical resilience. Your joint flexibility, overall bone density, posture, and dental health urgently need regular, highly serious medical attention and care. Enforcing absolute, iron-clad discipline in your daily dietary and health routines creates an incredibly strong, virtually unbreakable foundation for enduring, long-lasting physical well-being. Aging processes may seem apparent now, but proper care will reverse these effects.",
  mars_1st:
    "Exceptionally high physical energy, incredible stamina, and robust, undeniable vitality heavily mark this highly active period. Your peak athletic performance and physical strength are easily achieved when your intense energy is channeled properly into rigorous training. You must aggressively guard against sudden head injuries, severe migraines, high fevers, and acute bodily inflammation. Engaging in regular, exhausting physical activity is absolutely not optional—it's utterly essential for managing and grounding your incredibly powerful, overwhelming energy levels.",
};

export const HEALTH_SIGN_BLOCKS = {
  mars_aries:
    "Head-related health issues, chronic migraines, sinus pressure, and acute inflammatory conditions require your immediate, serious attention. Implementing regular, highly effective headache management protocols, practicing aggressive stress reduction techniques, and strictly consuming cooling, anti-inflammatory foods heavily support your well-being. Engaging in massive physical exercise in highly controlled, moderate amounts deeply helps effectively channel your massive excess physical and mental energy constructively.",
  saturn_capricorn:
    "Your overall bone health, skeletal structure, joint flexibility, and fundamental structural physical well-being desperately need incredibly consistent, daily attention. Engaging heavily in weight-bearing exercises, maintaining highly calcium-rich nutrition, and implementing strict, regular stretching or yoga routines actively prevent severe chronic stiffness and perfectly maintain your vital mobility throughout this highly demanding, disciplined health period.",
  moon_cancer:
    "Your delicate digestive health, gut microbiome, and highly emotional, comfort-seeking eating patterns require massive, conscious awareness. Issues involving the stomach lining, excess stomach acid, severe water retention, and intense hormonal imbalances benefit immensely from adopting highly mindful eating habits and practicing deep emotional self-regulation. Creating an incredibly nurturing, safe, and relaxing home environment profoundly supports your overall physical and mental health.",
};

export const HEALTH_PERSONAL_YEAR_BLOCKS: Record<number, string> = {
  1: "This is a profound year of entirely renewed, incredible health vitality and physical rebirth. You must aggressively start completely new, highly ambitious fitness regimens, successfully adopt radically healthier dietary habits, and heavily prioritize expensive, comprehensive preventive medical care. Your physical body responds exceptionally quickly and positively to all fresh, disciplined health initiatives, new diets, and massive lifestyle changes initiated exactly this year. Do not wait for a crisis to get healthy.",
  2: "Your overall health benefits exponentially from prioritizing deep, restorative rest and engaging in gentle, partnership-based physical activities. Practicing restorative Yoga, participating in couples' exercises, and establishing gentle, highly predictable daily routines perfectly sustain your physical well-being. Your delicate, shifting emotional balance directly, significantly, and immediately influences your physical health—you must actively and equally nurture both your mind and body with meticulous care and patience.",
  3: "Engaging heavily in joyful social activities, lighthearted entertainment, and laughter massively boosts your mental health and overall emotional well-being. Uninhibited creative expression, art therapy, and music serve as incredibly powerful, profound physical and psychological therapy right now. Participating in joyful, rhythmic movement, dance classes, and highly active group fitness activities beautifully energize your physical body while profoundly nourishing your inner spirit.",
  4: "You absolutely must establish totally solid, unshakeable physical health foundations this year. Implementing highly consistent, boring daily routines, scheduling comprehensive, regular medical check-ups, and committing to disciplined, scheduled exercise absolutely create lasting, lifelong wellness habits. Your amazing body richly and visibly rewards highly systematic, predictable care—you must actively build strict health habits that immediately become second nature and non-negotiable.",
  5: "Your overall health literally thrives through constant variety, physical movement, and engaging in entirely new, exciting experiences. You must actively try radically different exercise styles, boldly explore new ethnic cuisines, and enthusiastically embrace highly active, adventure-based wellness activities like hiking or travel. However, you must actively, consciously avoid physical recklessness, extreme sports injuries, and dietary excess while thoroughly enjoying the chaotic, massive energy of change.",
  6: "The overall health of your immediate family members heavily becomes a major priority right alongside your own personal wellness journey. You must actively work to create highly healthy, toxin-free home environments, consistently cook highly nutritious, organic meals, and actively foster your family's holistic well-being. Your naturally nurturing, deeply caring nature extends easily and naturally to carefully managing and caring for the physical and emotional health of others.",
  7: "Deep, esoteric, and quiet inner health practices gain massive, undeniable prominence in your life this year. Intensive meditation retreats, deep psychological therapy, and focusing heavily on spiritual wellness profoundly heal both your complex mind and physical body. Seeking deep solitude, quiet reflection, and actively disconnecting from the noisy world quickly restores your depleted energy reserves and constantly provides absolute, crystal-clear clarity about your true medical and health needs.",
  8: "Superb health richly rewards those who take absolute, uncompromising charge of their physical bodies. You must heavily invest in premium, top-tier healthcare, rapidly adopt intense, heavy strength-building routines, and highly prioritize comprehensive, expensive executive health screenings and blood panels. Your incredibly cold, highly disciplined, and metric-driven approach to health creates extremely powerful, virtually bulletproof physical resilience.",
  9: "Your physical health completely finishes a massive, natural nine-year cycle. You must absolutely, ruthlessly release all highly unhealthy habits, toxic addictions, and negative thought patterns that completely no longer serve you or your body. Engaging heavily in intense physical detox programs, profound emotional release work, and exclusively utilizing holistic healing modalities bring massive closure and perfect preparation for the entirely renewed, incredible vitality awaiting you.",
};

export const HEALTH_MONTHLY_BLOCKS: Record<number, string> = {
  1: "January is absolutely perfect for meticulously setting massive, yearly health goals and immediately starting entirely new, aggressive fitness programs. The harsh cold weather demands your intense, focused attention to boosting immunity, maintaining joint flexibility through stretching, and fiercely protecting your delicate respiratory health. Consuming nutrient-dense, warm bone broths, healing herbal teas, and establishing highly rigorous, daily indoor exercise routines perfectly support your overall winter wellness.",
  2: "February deeply calls for immense patience, gentleness, and self-compassion regarding your ambitious health goals. Engaging in gentle, highly consistent, daily exercise always produces far better, longer-lasting results than engaging in sudden, intense, exhausting bursts of extreme activity. Delicate seasonal transitions may significantly affect your overall mood—utilizing high-quality light therapy, prioritizing deep social connections, and consuming warm, highly comforting nutrition maintain your emotional and physical balance.",
  3: "March powerfully and beautifully brings entirely renewed, surging physical energy into your body. Engaging in highly active outdoor activities, undertaking massive, vigorous spring cleaning, and significantly increasing your daily physical movement align perfectly with nature's awakening, energetic rhythms. Severe seasonal allergies may urgently need strict medical management—you must stay highly proactive with appropriate antihistamines and maintain extreme air quality awareness inside your home.",
  4: "April crucially sustains your highly active, massive health momentum. Engaging heavily in very vigorous exercise, competitive sports activities, and thrilling outdoor adventures perfectly suit the highly energized season. However, you must aggressively guard against severe physical overexertion and acute sports injuries by warming up extensively, stretching properly, and staying acutely, continuously aware of your actual physical limits during all intense activities.",
  5: "May heavily and beautifully favors focusing on aesthetics, beauty treatments, deep self-care, and highly restorative health practices. Upgrading your skin care routines, indulging in luxurious spa treatments, and practicing deep relaxation techniques optimally harmonize your complex body and mind. Comprehensive reproductive health awareness, tracking hormonal cycles, and heavily prioritizing absolute hormonal balance highly deserve your intense attention during this deeply harmonious, balanced month.",
  6: "June brightly highlights extreme mental agility and the urgent need to fiercely protect your highly sensitive nervous system health. You must stay incredibly, consistently well-hydrated, aggressively take highly regular, forced breaks from all digital screens, and practice deep mindfulness daily. Your delicate digestive health benefits enormously from maintaining highly regular, predictable meals, deeply chewing your food, consuming massive amounts of fiber-rich foods, and utilizing stress-reducing, deep breathing exercises.",
  7: "July strictly requires your massive, undivided attention to your overall emotional health, psychological well-being, and delicate water balance. You must stay incredibly well-hydrated with pure minerals, closely monitor your sleep quality and duration, and immediately address any severe, disruptive hormonal fluctuations. Engaging in swimming, relaxing water-based therapies, taking long baths, and implementing highly calming, rigid evening routines perfectly support your overall well-being and restore your vitality.",
  8: "August massively boosts your baseline vitality, heart rate, and powerful constitutional strength. Engaging in rigorous, heavy cardiovascular exercise, practicing extreme sun exposure management, and closely monitoring your heart health are absolute, non-negotiable priorities. Focusing on eye care, wearing sunglasses, and applying aggressive skin protection become highly important. Your natural physical energy levels absolutely peak right now—you must channel them productively into fitness.",
  9: "September is absolutely ideal for scheduling comprehensive, full-body health assessments, heavy blood panels, and advanced preventive medical screenings. Paying highly detailed, microscopic attention to your exact daily nutrition, conducting massive supplement reviews, and actively engaging in complete lifestyle optimization yields incredible, measurable, undeniably positive improvements. Your mental health benefits massively from deep journaling, ongoing psychological therapy, and implementing highly structured, daily self-reflection practices.",
  10: "October beautifully brings deeply balanced, robust physical health through implementing highly harmonious, predictable daily routines. Engaging in partner-based fitness activities, attending group classes, and joining supportive social wellness programs massively enhance your daily workout motivation. Your delicate kidney function and overall hormonal health highly deserve your strict, immediate medical attention. Mastering stress management through engaging in art therapy, listening to music, and deep nature connection perfectly restores your physical equilibrium.",
  11: "November rapidly expands your overall health horizons through eager exploration and highly enthusiastic learning. You must actively try radically new health practices, enthusiastically attend holistic wellness workshops, and boldly explore unconventional, alternative healing modalities. Your incredibly open-mindedness toward massive health innovation, bio-hacking, and new science leads directly to discovering highly effective, incredibly, personally meaningful wellness approaches that genuinely change your life.",
  12: "December strongly and unavoidably calls for massive physical rest, deep psychological reflection, and aggressive immune system strengthening. The inevitable, intense holiday stress definitively requires highly proactive, aggressive management through deep daily meditation, very gentle exercise routines, and enforcing strictly adequate, extended sleep schedules. Openly celebrate the entire year's massive health achievements and fitness victories while decisively setting powerful, ambitious intentions for your continued, even better wellness in the upcoming new year.",
};
