/**
 * Love / Relationship Interpretation Blocks
 */

export const LOVE_DASHA_BLOCKS = {
  saturn_active:
    "All romantic relationships will require an immense amount of unwavering commitment, extreme patience, and profound, adult maturity during this demanding period. Highly superficial connections, casual dating, or fleeting summer romances will quickly fade away, unable to withstand Saturn's intense pressure testing. Conversely, much deeper, truly substantial bonds will strengthen incredibly and permanently through happily sharing heavy responsibilities, facing difficult trials together, and cultivating massive mutual respect. Long-term, committed partnerships benefit enormously from strict, boring, but highly effective structural planning—you must sit down together and aggressively discuss your long-term shared goals, meticulously construct detailed financial planning as a couple, and establish highly reliable, comforting daily routines together. The love you build right now is not based purely on fleeting, dizzying passion, but rather on the undeniable, rock-solid bedrock of unwavering reliability, absolute trust, and enduring loyalty through thick and thin. This is the absolute best time for cementing a permanent, unbreakable commitment or peacefully ending a relationship that has clearly run its karmic course.",
  jupiter_active:
    "Your overall love life, romantic endeavors, and long-term partnerships receive an incredibly positive, massive wave of expansive, joyful energy. Entirely new, exciting relationships formed right now carry profound, almost cosmic deeper meaning and may strongly involve intense spiritual, intellectual, or highly philosophical connections. Existing, healthy partnerships grow massively and beautifully through excitedly sharing new learning experiences, undertaking extensive international travel together, and actively expanding your shared, mutual wisdom. Your incredibly generous, open heart and radiant optimism naturally attract highly high-quality partners who deeply appreciate your authenticity, unshakeable integrity, and genuine, profound emotional connection. This is an absolutely golden, extremely favorable period for joyous engagements, beautiful weddings, or joyously renewing vows in your existing marriage. You fundamentally and joyfully believe in the absolute ultimate goodness of love right now, and the universe perfectly mirrors that beautiful belief right back to you.",
  mars_active:
    "Incredible, intense, and sometimes explosive passion completely characterizes all your romantic interactions right now. Searing physical attraction, undeniable magnetic chemistry, and powerful sexual energy run at an all-time high, but you absolutely must aggressively guard against falling into highly destructive, conflict-driven, competitive relationship dynamics. You must consciously and actively channel this massive, fiery romantic energy into highly adventurous, thrilling shared experiences that successfully build excitement, adrenaline, and fun without inevitably creating toxic, destructive communication patterns. Brutally honest, completely direct communication is the absolute only way to successfully prevent massive, relationship-ending misunderstandings during this highly volatile, heat-filled cycle. You fiercely want what you want right now, but you must actively remember that true partnership requires patient compromise, not just aggressive, selfish conquest. Arguments can escalate quickly, but passionate reconciliations are equally intense.",
  venus_active:
    "Pure love, sweet romance, and beautiful, highly harmonious partnership absolutely flourish for you in every conceivable way right now. Entirely new, exciting relationships begin easily with immense, undeniable charm, sweet flirtation, and highly powerful, physical attraction, while existing, long-term partnerships joyfully and miraculously rediscover their lost intimacy, spark, and shared joy. Actively engaging in highly artistic shared activities, offering massive, grand romantic gestures, and mutually cultivating a deep aesthetic appreciation for life massively strengthen your unshakeable bond with your current partner. This is a rare, exceptionally favorable, almost magical period for all delicate matters of the heart, where finding true, lasting love feels wonderfully, surprisingly effortless. You radiate a powerful, irresistible, magnetic aura that effortlessly draws romantic admirers and deep affection toward you from all directions. Surround your relationship with beauty, fine dining, and absolute, luxurious pleasure.",
  mercury_active:
    "Crystal-clear, highly articulate communication officially becomes the absolute, foundational bedrock of all your romantic and relationship success right now. You absolutely must express your complex feelings clearly and directly through beautifully written words, heartfelt letters, and engaging in deep, highly meaningful, intellectual conversations with your partner. Absolute intellectual compatibility, shared mental curiosity, and a meeting of the minds gain massive importance over purely physical attraction in your overall partner selection. Highly active online connections, sophisticated dating apps, and all technology-facilitated relationships may suddenly play an incredibly significant, highly successful role in vastly expanding your overall love life. Love is definitively found through the mind, shared ideas, and witty banter during this cycle, not just through the physical heart. A partner who cannot match your quick intellect or stimulate your active mind will quickly and inevitably bore you to tears.",
  rahu_active:
    "Highly unconventional, deeply taboo, or entirely unpredictable romantic connections may suddenly and shockingly emerge, completely challenging all your past, traditional expectations of what love should look like. Engaging in massive cross-cultural relationships, navigating highly unusual, bizarre meeting circumstances, and entering into entirely non-traditional, highly modern partnerships bring you incredibly unique, life-altering romantic lessons. You must aggressively maintain absolute, crystal clarity about your core, non-negotiable moral values while simultaneously remaining highly, vulnerably open to experiencing love in its many diverse, sometimes shocking, and immensely surprising forms. Powerful, almost desperate obsessions and instantaneous, overwhelming attractions are highly likely, but you absolutely must ensure they are truly grounded in solid reality rather than fleeting, dangerous illusions. The exotic, the foreign, and the totally forbidden hold a massive, almost irresistible magnetic appeal for you right now.",
  ketu_active:
    "Deep-seated, very old, past relationship patterns and unresolved, painful romantic karma suddenly surface for massive review and final, total release. Highly intense, undeniably karmic connections may suddenly bring you significant, painful learning through intense, short-lived, but profoundly transformative romantic encounters that change your soul forever. Actively cultivating a profound sense of total detachment from specific relationship outcomes paradoxically and miraculously creates the vast psychological space required for vastly more authentic, deeply spiritually aligned partnerships to finally develop. You must bravely, willingly, and completely let go of deeply unhealthy, toxic attachments, co-dependent behaviors, and past, lingering heartbreaks to finally move forward and obtain true romantic liberation. Solitude may actually feel vastly more comforting and healing to you than forcing a superficial, unfulfilling romance right now.",
  sun_active:
    "Massive, radiating confidence, absolute self-assurance, and undeniable personal sovereignty powerfully attract high-level romantic attention toward you. Your natural, warm charisma effortlessly draws numerous admirers, and your strong, unshakeable leadership qualities actively make you an incredibly highly attractive, desirable partner. However, you absolutely must learn to successfully balance your immense need for dramatic self-expression and being the center of attention with a genuine, humble attentiveness to your partner's complex emotional needs to maintain highly harmonious, balanced relationship dynamics. A relationship cannot survive if you treat your partner merely as an invisible audience member to your own grand life performance. True, lasting love right now requires two strong, fully realized individuals standing confidently side-by-side as absolute equals.",
  moon_active:
    "Incredible emotional depth, highly intuitive empathy, and profoundly nurturing qualities entirely define and structure all your romantic connections right now. Your extreme, beautiful sensitivity and genuinely caring, protective nature effortlessly create incredibly deeply intimate, unbreakable emotional bonds with your lover. Cultivating a quiet, unspoken, highly intuitive understanding of your partner's most hidden emotional needs massively and profoundly strengthens the core relationship. Going on highly romantic moonlit dates, engaging in tearful, deep emotional conversations, and prioritizing quiet, intensely private domestic intimacy bring you the most profound, soul-satisfying romantic satisfaction. You absolute crave total emotional merging, extreme psychological safety, and absolute, unconditional acceptance from your partner above all other flashy, superficial romantic displays.",
};

export const LOVE_HOUSE_BLOCKS = {
  venus_7th:
    "Legal partnerships, deeply committed relationships, and the holy institution of marriage receive incredibly strong, universally favorable, an wonderfully protective planetary influences. Whether you are actively seeking a new mate or aggressively trying to strengthen an existing relationship, this beautiful placement creates massive, undeniable harmony, intense physical attraction, and profound mutual appreciation. Hearing joyful wedding bells, formalizing a massive commitment, or deciding to finally move in together are especially, incredibly well-supported and highly likely to result in lifelong happiness during this magical period.",
  mars_7th:
    "Immense, fiery passion and extreme, sometimes overwhelming intensity heavily mark all your romantic partnerships and closest alliances. While the raw physical attraction and sexual energy are incredibly strong, you absolutely must aggressively and consciously guard against extreme possessiveness, toxic jealousy, and picking unnecessary, competitive fights with your spouse. You must actively, deliberately channel this massive, explosive passion into highly thrilling, shared physical adventures and making bold, decisive relationship decisions that effectively strengthen your core bond rather than actively destroying it from the inside out.",
  jupiter_7th:
    "Your core partnerships and marriage experience massive, joyful expansion largely through actively acquiring shared philosophical wisdom, undertaking extensive international travel together, and prioritizing deep, mutual spiritual growth. Your overall marriage prospects improve significantly and rapidly. Your ideal destined partner confidently brings immense, profound wisdom, vast generosity, and deep philosophical depth directly into the primary relationship. Massive international, cross-cultural love connections or marrying someone from a completely different religious background are particularly, incredibly favored and karmically destined to bring you great joy.",
  saturn_7th:
    "All your romantic relationships will face grueling, significant tests of ultimate commitment, unshakeable loyalty, and prolonged endurance. Highly committed, long-term partnerships will absolutely strengthen and become virtually unbreakable through triumphing over these difficult challenges, while shallow, superficial, or fundamentally flawed connections will completely, naturally, and painfully fall away. Experiencing a delayed, later-in-life marriage or a frustratingly slow-building, cautious romance ultimately and definitely creates a significantly deeper, vastly more resilient, and permanent bond than any hasty, rushed youthful affair ever could.",
  rahu_7th:
    "Highly unusual, surprisingly modern partnership dynamics and entirely unconventional, somewhat taboo romantic connections strongly emerge in your life. Heavily technology-facilitated relationships, online dating successes, and wildly unpredictable cross-cultural romances bring you incredibly exciting, paradigm-shifting, but highly unpredictable romantic experiences. You must actively fight to maintain absolute, grounding authenticity while enthusiastically exploring completely new, progressive forms of modern partnership that completely defy traditional societal expectations of marriage.",
  venus_5th:
    "Sweet new romance, highly creative artistic expression, and profoundly joyful, fun-filled love affairs are beautifully and powerfully highlighted for you. Experiencing overwhelming first love feelings, engaging in highly artistic collaborations that hold massive, undeniable romantic overtones, and enjoying playful, flirtatious romantic energy bring you immense delight, deep joy, and profound emotional fulfillment. This is a time for actively dating, having pure, unadulterated fun, and remembering exactly how beautiful and carefree new love is supposed to feel before the heavy responsibilities of life set in.",
};

export const LOVE_PERSONAL_YEAR_BLOCKS: Record<number, string> = {
  1: "This represents a definitive, powerful year of entirely new romantic beginnings and ushering in completely fresh, exciting relationship energy. It is the absolute perfect, optimal time for boldly starting totally new relationships or aggressively revitalizing highly stagnant, existing ones with your entirely renewed sense of fierce independence and high self-confidence. Your bold, totally authentic, and unapologetic self-expression flawlessly and naturally attracts genuinely compatible, high-quality partners who love you exactly for who you truly are, not who you pretend to be. Do not wait for love to find you; boldly go out and actively forge the deeply passionate romantic life you absolutely deserve.",
  2: "Extreme patience, high-level diplomacy, and deep partnership entirely define all your romantic themes for this year. Existing, long-term relationships significantly deepen through forcing extreme cooperation, practicing endless compromise, and developing profound, unspoken emotional attunement with your partner. This is definitively a year reserved for actively listening much more than you speak, and for deeply nurturing your delicate love through offering small, highly consistent, daily romantic gestures. Do not try to force massive, dramatic relationship changes; instead, focus entirely on creating absolute peace, perfect harmony, and mutual understanding.",
  3: "Pure joy, massive social connection, and highly fun, lighthearted romantic experiences characterize your vibrant love life this year. Engaging heavily in harmless flirtation, actively dating, and pursuing highly fun, lighthearted romantic experiences bring you immense, undeniable happiness and a renewed zest for life. Your highly uninhibited creative self-expression and massive, glowing social charisma effortlessly make you magnetically, almost irresistibly attractive to numerous, high-quality potential partners. This is the absolute best year for enjoying massive, romantic fun rather than attempting to force heavy, serious, or burdensome long-term commitments too early.",
  4: "Your primary focus must be on aggressively building highly stable, rock-solid relationship foundations entirely through demonstrating unwavering, practical commitment and total reliability. You must openly and seriously discuss all long-term plans, fairly divide all shared responsibilities, and formally establish the exact, desired structure of your relationship with your partner. The immense, serious, and sometimes boring hard work deliberately invested into actively securing your relationship stability now absolutely pays massive, lasting dividends for many decades to come. Love is treated as a serious verb and a daily duty this year, not just a fleeting, dizzying emotion.",
  5: "Expect massive, highly exciting, and somewhat terrifying changes in your entire love life—suddenly encountering completely new relationships, experiencing highly unexpected, shocking romantic encounters, or undergoing dramatic, total transformations in your existing partnerships. You must actively, enthusiastically embrace absolute personal freedom and wild adventure while still fiercely maintaining your strict emotional integrity and enforcing brutally honest communication. An overly suffocating, rigid, or highly restrictive relationship will absolutely not survive this intensely volatile, chaotic cycle; both you and your partner must grant each other the vast space required to completely breathe, grow, and wildly explore.",
  6: "Profound love is found entirely through selfless service, taking on heavy familial responsibility, and providing deep, unconditional nurturing care for another human being. Entering into a formal marriage, actively starting a family, or significantly deepening an existing domestic partnership are the absolute, central, undeniable themes of this year. Your beautiful, selfless willingness to happily sacrifice your own immediate needs for the ultimate well-being of your loved ones creates profoundly meaningful, utterly unbreakable romantic bonds. Your primary romantic goal is to create a beautiful, perfectly harmonious, and completely safe domestic sanctuary for your sacred partnership to permanently thrive within.",
  7: "This represents a deeply introspective, highly quiet year meant for profoundly analyzing your love experiences—understanding your own incredibly deep, repetitive romantic patterns, hidden psychological wounds, and unexpressed desires at a much deeper, almost microscopic level. Engaging in solitary, quiet reflection on exactly what you truly, deeply need in a lifelong partner perfectly guides you forward toward establishing vastly more authentic, spiritually aligned, and deeply fulfilling connections in the future. You may strongly and naturally prefer deep, comforting solitude over engaging in superficial, meaningless dating right now; actively use this quiet time to completely and permanently heal your own heart.",
  8: "Complex power dynamics, control issues, and financial matters within your relationships absolutely require your highly conscious, active management and assertion. Practicing extreme assertiveness in clearly and confidently expressing exactly what your hard romantic needs are leads directly to significantly more fulfilling, balanced, and respectful partnerships. Offering substantial, material expressions of your love and orchestrating massive, highly expensive, grand romantic gestures have a significantly positive, deeply impressive impact on your partner. You ultimately treat your core romantic partnership exactly like a highly successful, well-managed merger, ensuring that both parties equally and massively profit emotionally and financially.",
  9: "You have finally reached the profound, necessary completion of massive, nine-year relationship cycles—this requires you to completely and permanently end all highly unhealthy, toxic romantic patterns and absolutely forgive all past, deep relationship hurts that still haunt you. You must actively prepare the ground for entirely new, healthy love by completely and finally releasing all your heavy, lingering emotional baggage. Offering deep, compassionate romance and practicing totally selfless, unconditional love without expecting anything in return bring you the absolute deepest, most profound soul satisfaction imaginable. Let go of the past completely with grace and dignity.",
};

export const LOVE_MONTHLY_BLOCKS: Record<number, string> = {
  1: "January definitively sets your massive, overarching romantic intentions for the entire year ahead. You must deeply and quietly reflect on exactly what you truly, desperately want from love right now and definitively establish highly meaningful, non-negotiable relationship goals. The harsh cold winter weather beautifully creates perfect opportunities for enjoying highly cozy, physical intimacy and having incredibly deep, hours-long emotional conversations that massively, permanently strengthen your core emotional bonds. Do not rush into anything new; plan your romantic strategy carefully.",
  2: "February naturally, heavily emphasizes profound romantic love, entirely through massive Valentine's Day energy and a universal focus on deep partnership. You absolutely must express your most complex, hidden feelings completely openly and actively orchestrate highly romantic, memorable experiences that significantly deepen your connection. Both entirely new and heavily established relationships benefit immensely from your highly intentional, focused, and undivided romantic attention and grand, sweeping gestures. Lavish your partner with undivided affection.",
  3: "March rapidly brings highly passionate, fiery, and slightly aggressive romantic energy back into your life. Initiating bold, fearless expressions of romantic interest and planning highly adventurous, physically demanding outdoor dates create massive, undeniable excitement. Uncontrollable physical attraction and raw sexual chemistry intensify significantly—you absolutely must actively channel this massive, fiery energy into profoundly deepening your actual intimacy rather than aimlessly pursuing shallow, superficial, fleeting physical connections.",
  4: "April crucially sustains the previous month's high romantic momentum entirely through highly active, physically demanding shared experiences. Planning massive outdoor adventures, booking international travel plans, and executing highly physically engaging dates build incredible, undeniable partnership strength. Practicing brutally clear, totally direct, and uncompromising communication about exactly what your hard romantic needs are successfully prevents massive, destructive misunderstandings during this highly energized, slightly explosive month.",
  5: "May beautifully and softly blossoms with unparalleled romantic beauty, profound aesthetic appreciation, and intensely deep, physical sensual connection. Planning highly expensive date nights, booking luxurious romantic getaways, and actively enjoying shared artistic or musical experiences massively strengthen your core bond. Offering massive physical affection, buying beautiful gifts, and cultivating a deep aesthetic appreciation for your partner bring immense, undeniable joy. This is easily one of the entire year's most highly, universally romantically favorable and successful months for love.",
  6: "June brightly and sharply highlights the highly intellectual, extremely communicative, and deeply analytical aspects of modern romance. Having hours of deep, philosophical conversations, writing profound, highly articulate love letters, and engaging in highly meaningful, intellectual exchanges build immense, unshakeable emotional and mental intimacy. All long-distance relationships and highly technology-facilitated online connections see incredibly positive, massive, and highly encouraging developments during this intensely mentally active period.",
  7: "July profoundly deepens all emotional, unspoken romantic bonds entirely through practicing extreme emotional vulnerability and offering unconditional, maternal nurturing. You absolutely must bravely share your deepest, most hidden feelings and actively create a space of absolute, unbreakable emotional safety with your partner. Fostering intense domestic romance—such as cooking elaborate, multi-course home-cooked dinners, hosting cozy movie nights, and enjoying intensely quiet, deeply emotional evenings—brings the most profound, soul-satisfying romantic satisfaction possible.",
  8: "August powerfully and brightly brings highly confident, incredibly radiant, and slightly dramatic romantic energy into your aura. You absolutely must express your deepest romantic desires loudly and boldly, and confidently take the absolute lead in making all major relationship decisions. Your immensely natural, glowing charisma effortlessly and powerfully attracts massive romantic attention and numerous high-quality admirers from all directions. Executing massive, highly theatrical grand romantic gestures and staging bold public expressions of your love are incredibly well-received.",
  9: "September sharply brings incredibly analytical clarity, cold logic, and a critical eye to all your romantic relationships. You absolutely must assess your overall relationship health brutally honestly and actively, immediately make any deeply necessary, difficult adjustments. Engaging in highly practical romance—such as meticulously sorting out all shared finances, managing the household budget, and logically planning concrete future steps—immensely and permanently strengthens your overall partnership's practical foundations.",
  10: "October heavily emphasizes achieving absolute balance, ultimate fairness, and true, equal partnership in all romance. Practicing extreme fairness, demanding total reciprocity, and fostering deep, mutual respect completely define your healthy, highly balanced romantic dynamics right now. Actively attending high-end social events and engaging heavily in shared cultural or artistic experiences together beautifully create lasting, shared memories that significantly enrich and deepen your ongoing, beautiful love story.",
  11: "November rapidly and beautifully expands your overarching romantic horizons precisely through making deep philosophical connections and seeking wild adventure. You absolutely must travel internationally with your partner, actively explore new, shared spiritual practices, and spend hours discussing life's deepest, most profound existential questions together. All long-distance romantic connections and relationships bridging massive cultural divides see incredibly positive, highly significant, and extremely validating developments this month.",
  12: "December beautifully and warmly brings profound romantic warmth entirely through establishing shared holiday traditions and focusing on highly family-centered, unconditional love. You must deeply reflect on the entire year's massive romantic journey and actively, openly express immense, profound gratitude for your partner's unwavering presence in your life. Offering massive, thoughtful year-end romantic gestures perfectly creates lasting, deeply emotional memories and fosters unbreakable, intimate closeness.",
};
