/**
 * Personal Growth Interpretation Blocks
 *
 * Reusable, deterministic text blocks for personal growth predictions.
 * Includes monthly-specific blocks for granular month-by-month guidance.
 */

export const PERSONAL_GROWTH_DASHA_BLOCKS = {
  saturn_active:
    "Your personal growth during this cycle is forged through discipline, resilience, and taking responsibility for your life's structure. You are learning the profound value of delayed gratification and consistent effort. Superficial self-help methods will not suffice now; you are building a mature, enduring character. You may face delays or restrictions, but these are essential tests of your commitment to long-term goals. Embrace challenges as opportunities to strengthen your psychological boundaries and overcome deep-seated fears. You are shedding youthful naivety and stepping into a period of profound self-mastery. True growth comes from acknowledging reality and steadily working to improve it.",
  jupiter_active:
    "This is a vibrant cycle of intellectual expansion, optimism, and broadening your horizons. Personal growth comes effortlessly as you feel a deep hunger for learning, travel, or understanding different philosophies of life. Your worldview is expanding rapidly, and you are likely to discover hidden talents or a renewed sense of purpose. Seek out mentors, teachers, and experiences that challenge your current paradigms. Generosity, ethical behavior, and maintaining a positive mindset will attract profound opportunities for self-discovery. You are developing a deep, abiding faith in your own potential and the universe's abundance. Embrace the journey of lifelong learning.",
  mars_active:
    "Your path to self-improvement is characterized by dynamic action, courage, and asserting your individuality. You grow rapidly when you face your fears head-on, overcome obstacles, and channel your energy into independent projects. This is a time to develop your physical vitality, willpower, and competitive spirit in a healthy way. You are learning to stand up for yourself and pursue your desires without hesitation. Be mindful of impatience or unnecessary conflict; true personal growth now involves mastering your passions and directing them constructively. You have the raw energy to break through personal limitations that have held you back for years.",
  venus_active:
    "Personal growth blossoms through cultivating harmony, self-love, and appreciation for beauty in all its forms. You evolve by creating balanced relationships, refining your aesthetic tastes, and finding joy in the present moment. This is a period to heal issues related to self-worth, pleasure, and artistic expression. Connecting with others through diplomacy, empathy, and shared creative endeavors will bring profound personal insights. You are learning that growth doesn't always require struggle; it can also occur through grace, ease, and cultivating a peaceful inner state. Indulge your senses and embrace the art of living well.",
  mercury_active:
    "Your mind is your primary vehicle for personal evolution right now. Growth comes through rigorous intellectual curiosity, improving your communication skills, and adapting to new ideas. This is an excellent time for studying new subjects, engaging in stimulating conversations, and refining your ability to articulate your deeper feelings. You are learning to synthesize diverse information and approach problems with logical clarity. Flexibility and a willingness to change your perspective are crucial. You may find that writing, teaching, or networking accelerates your process of self-discovery. Sharpen your intellect and seek objective truth.",
  rahu_active:
    "Prepare for a period of rapid, sometimes chaotic, and highly unconventional personal development. Rahu pushes you out of your comfort zone, urging you to break societal norms and embrace your unique, perhaps eccentric, individuality. You may be drawn to foreign cultures, new technologies, or radical new ways of thinking. Growth comes through embracing the unknown and trusting your instinctual drives, even if they seem illogical to others. Be cautious of obsessions or seeking fulfillment purely in material achievements. Authentic growth requires you to navigate this intense period of expansion with self-awareness and grounding to avoid losing yourself in illusions.",
  ketu_active:
    "This is a profound cycle of inward growth, emotional release, and spiritual introspection. You are growing by letting go—shedding past identities, releasing old attachments, and dissolving the ego. This process of deep internal restructuring can initially feel like a loss, but it is a necessary part of your soul's evolution. Solitude, meditation, and psychological healing are highly favored. You are learning to trust your deepest intuition and detach from external validation. True personal power during this time comes from understanding your subconscious motivations and realizing you are more than your worldly achievements. Surrender is the highest form of growth now.",
  sun_active:
    "Your personal growth centers on developing your core identity, authentic self-expression, and leadership abilities. This cycle demands that you step into the 'light' and own your unique strengths and talents. You are growing in confidence, vitality, and your capacity to inspire others through your example. Overcoming issues of ego, arrogance, or the need for constant attention is part of this journey. The goal is to cultivate a radiant, generous sense of self that illuminates the lives of those around you. You are discovering what it truly means to shine and to be the sovereign ruler of your own life.",
  moon_active:
    "Emotional intelligence, empathy, and nurturing your inner child are the keys to your personal development now. You grow deepest when you allow yourself to be vulnerable, explore your subconscious feelings, and heal family dynamics. This is a powerful time for psychological healing, focusing on self-care, and understanding the emotional needs of yourself and others. Growth is not linear right now; it is cyclical and deeply tied to your emotional states. Learn to trust your intuition and honor your need for emotional security. Cultivating a rich, compassionate inner life is your primary task.",
};

export const PERSONAL_GROWTH_HOUSE_BLOCKS = {
  saturn_2nd:
    "Your greatest lessons in self-worth revolve around financial discipline, managing resources, and recognizing the true value of your skills. You grow by establishing a solid, practical foundation for your security and overcoming fears of scarcity.",
  jupiter_5th:
    "Personal growth explodes through creative self-expression, joyous play, and connecting with children or your own inner child. You expand your sense of self by taking creative risks and joyfully sharing your unique talents with the world.",
  mars_3rd:
    "You grow through courageous communication, intellectual debate, and taking decisive action on your ideas. Developing your skills, traveling short distances, and boldly asserting your opinions build your confidence and personal agency.",
  venus_7th:
    "Your evolution is intimately tied to your significant relationships and partnerships. You learn the most about yourself through the mirror of another person. Cultivating balance, diplomacy, and mutual respect in your connections brings profound personal maturation.",
  mercury_11th:
    "Your intellectual horizons expand through community involvement, networking, and engaging with progressive ideas. You grow by collaborating with diverse groups of people and developing innovative solutions to collective challenges.",
  sun_1st:
    "Your personal development journey is a bold quest for authentic selfhood. You are driven to project your core truth into the world with confidence and vitality. Your primary task is to lead by example and radiate your unique individuality without apology.",
  moon_12th:
    "Deep personal growth occurs in solitude, through psychological exploration, and connecting with your subconscious mind. You grow by retreating from the world to process hidden emotions, heal deep wounds, and develop a profound, quiet inner strength.",
  rahu_9th:
    "Your thirst for personal expansion drives you to explore foreign cultures, exotic philosophies, and unconventional belief systems. You grow by stepping outside the familiar and passionately seeking a broader understanding of life's vast possibilities.",
  ketu_3rd:
    "You grow by detaching from superficial communication and mental busyness. Your development requires you to trust your deep, intuitive knowing over intellectual logic. You are learning to let go of the need to constantly explain yourself.",
  saturn_8th:
    "Profound personal transformation comes through confronting deep psychological fears, issues of trust, and the mysteries of life and death. You grow by enduring emotional intensity and emerging with a resilient, unsinkable inner strength.",
};

export const PERSONAL_GROWTH_SIGN_BLOCKS = {
  jupiter_aries:
    "Your approach to personal growth is pioneering, enthusiastic, and independent. You expand your identity by initiating new projects, taking risks, and fearlessly charging into the unknown. You inspire yourself and others through bold action.",
  saturn_libra:
    "Your deepest lessons involve creating true balance, fairness, and commitment in your relationships. You are cultivating a refined, mature sense of justice and learning the discipline required to maintain lasting, harmonious partnerships.",
  mars_capricorn:
    "You attack your personal development goals with relentless ambition, strategic planning, and immense self-control. Your drive for mastery is powerful. You grow significantly by channeling your intense energy into structured, long-term achievements.",
  venus_taurus:
    "Your personal evolution is deeply connected to your physical senses, the natural world, and cultivating true self-worth. You grow by creating stability, appreciating the finer things in life, and establishing a rock-solid foundation of self-love.",
  moon_scorpio:
    "Your journey of self-discovery requires profound emotional honesty and the willingness to explore your psychological depths. Superficial growth does not satisfy you; you seek total transformation and healing of your most hidden emotional wounds.",
};

export const PERSONAL_GROWTH_PERSONAL_YEAR_BLOCKS: Record<number, string> = {
  1: "This is a year of bold new beginnings and defining your independence. Your personal growth focuses on courage, initiative, and stepping into leadership roles in your own life. It is crucial to trust your instincts and take decisive action toward your individual goals. You are breaking free from the expectations of others to discover who you truly are. Embrace the discomfort of being a beginner and trust in your capacity to forge a new path. This is a time to prioritize your own needs and aspirations.",
  2: "Your personal development hinges on diplomacy, cooperation, and receptive listening. Growth this year comes not from forcing your will, but from harmonizing with others and adapting to your environment. You will learn profound lessons about patience, emotional sensitivity, and the power of partnership. Focus on resolving conflicts peacefully and cultivating deep, mutually supportive relationships. Pay attention to details and trust your intuition, as subtle shifts will bring significant inner changes. Seek balance in all things.",
  3: "This is a vibrant year of creative self-expression, joyful communication, and social expansion. Your personal growth accelerates when you allow yourself to play, create, and share your ideas enthusiastically with the world. Overcoming self-doubt and fear of judgment is a major theme. Embrace your unique voice through writing, speaking, or artistic pursuits. Surround yourself with positive, uplifting people who encourage your creativity. This is a time to celebrate your individuality and lighten your spirit.",
  4: "Your personal growth strategy must be grounded, disciplined, and practical this year. You are called to build a solid foundation for your future by organizing your life, managing your resources wisely, and establishing healthy routines. Growth comes through hard work, enduring commitment, and overcoming tendencies toward procrastination. This is an excellent time to focus on your physical health, your home environment, and your financial security. The effort you invest now creates the stability needed for future leaps.",
  5: "Prepare for a thrilling year of change, adventure, and personal liberation. Your growth occurs by breaking routines, exploring new ideas, and embracing the unexpected. Flexibility and an open mind are your greatest tools for development. You may feel a strong urge to travel, change careers, or learn unconventional subjects. The challenge is to navigate these changes without becoming scattered or irresponsible. Embrace the chaos as a necessary catalyst for discovering new dimensions of your potential.",
  6: "Your personal evolution centers around love, responsibility, and the harmonious integration of your home and family life. Growth comes through serving others, nurturing your close relationships, and creating a beautiful, peaceful environment. You are learning profound lessons about unconditional love, forgiveness, and healing old wounds. Prioritize your well-being while fulfilling your commitments to those who depend on you. Seek to bring balance and justice to your personal sphere.",
  7: "This is a deeply introspective year dedicated to self-analysis, intellectual pursuit, and spiritual refinement. The outer world slows down, demanding you focus on your inner life. Personal growth comes from solitude, deep study, meditation, and seeking philosophical truths. It is a time to evaluate your progress, refine your skills, and connect with your deeper intuition. Avoid forcing material outcomes; instead, cultivate wisdom and a deeper understanding of your own psyche. You are developing a quiet, unshakeable inner strength.",
  8: "Your focus turns toward personal empowerment, manifestation, and achieving material success. Growth this year requires you to step into your authority, assert your ambition, and handle power with integrity. You are learning to overcome limiting beliefs about money, success, and your own capabilities. Focus on strategic planning, organized effort, and making practical, long-term decisions. True growth involves recognizing your capacity to co-create your reality and managing your resources wisely for the highest good.",
  9: "This year marks the end of a major nine-year cycle of personal development. Growth occurs through completion, surrender, and deep emotional release. It is a time to tie up loose ends, forgive past grievances, and let go of relationships or situations that no longer serve your highest good. You are clearing the slate to prepare for the new beginnings of the next cycle. Embrace compassion, humanitarian ideals, and trust the process of transformation. Allowing old identities to dissolve is the profound growth lesson of this period.",
};

export const PERSONAL_GROWTH_MONTHLY_BLOCKS: Record<number, string> = {
  1: "January inaugurates your year with a strong focus on self-discipline and establishing your priorities. It is an excellent month to set clear, actionable goals for your personal development. Take a hard look at your habits and implement structures that support your long-term vision. Growth requires focused effort and a willingness to tackle difficult tasks. Acknowledge your responsibilities and face them head-on to build inner strength.",
  2: "February emphasizes emotional intelligence and the importance of your relationships in your growth journey. You learn the most about yourself through your interactions with close friends and partners. Practice active listening, empathy, and peaceful conflict resolution. Seek harmony in your environment and trust your gut feelings when making decisions. Patience is more valuable than forceful action right now.",
  3: "March brings a surge of creative energy and a desire for self-expression. This is a powerful month to break out of ruts and try new ways of thinking and doing. Your personal growth accelerates when you engage your imagination and communicate your ideas boldly. Don't be afraid to stand out or take unconventional approaches to your problems. Joy, social interaction, and optimism fuel your development.",
  4: "April demands that you ground your ideas into practical reality. The focus shifts to hard work, organization, and building a secure foundation for your life. Personal growth comes from attending to details, managing your finances responsibly, and maintaining consistent routines. It may feel restrictive, but this discipline is necessary to give your ambitions a solid structure. Focus on mastery and competence.",
  5: "May is a month of intellectual expansion, movement, and embracing change. You are encouraged to explore new philosophies, read challenging books, or travel to gain fresh perspectives. Personal growth requires flexibility and a willingness to adapt to new information. Break free from rigid thought patterns and engage in stimulating conversations. Curiosity is your greatest tool for self-discovery.",
  6: "June centers on matters of the heart, family dynamics, and creating emotional security. Deep personal growth occurs through nurturing yourself and others. Focus on healing relationships, forgiveness, and creating a harmonious domestic life. You may find profound insights by reflecting on your childhood and ancestral patterns. Prioritize self-care and ensure your emotional cup is full before pouring into others.",
  7: "July brings a strong need for solitude, introspection, and deep psychological work. You are drawn to analyze your subconscious motivations and seek deeper truths. This is a month for meditation, journaling, and stepping back from the social whirl. Personal growth comes from understanding the 'why' behind your actions and connecting with your intuition. Trust the wisdom that arises in quiet moments.",
  8: "August is a powerful month for asserting your ambition and stepping into personal authority. You are called to take charge of your life's direction and manifest your goals with confidence. Personal growth comes through facing your fears of failure or success, managing power dynamics, and acting with integrity. Focus on your long-term career or life path objectives and execute your plans decisively. You are stronger than you realize.",
  9: "September is a time of refinement, service, and intellectual analysis. You grow by critically evaluating your progress and making necessary adjustments. Focus on improving your skills, focusing on health and well-being, and organizing your life with greater efficiency. Helping others or engaging in charitable work brings a deep sense of personal fulfillment and humility. Seek perfection through daily, incremental improvements.",
  10: "October plunging you into a period of intense personal transformation and facing your shadow side. Growth requires profound emotional honesty and a willingness to release deep-seated fears or attachments. This is not a time for superficial changes; you are undergoing a psychological rebirth. Embrace the intensity, engage in deep therapeutic work if needed, and emerge stronger and more resilient. Let go of what you cannot control.",
  11: "November expands your vision and fills you with optimism and a desire for higher meaning. You grow by synthesizing the lessons of the past year into a broad philosophical framework. Seek out inspiring teachers, engage with diverse cultures, and share your own wisdom. Your faith in yourself and the universe is renewed. This is a month for expansive thinking and aligning your life with your highest ideals.",
  12: "December is a month of culmination, taking responsibility, and solidifying your character. You are asked to integrate all you have learned and apply it to the structures of your life. Growth comes through enduring commitment, achieving maturity, and setting a firm foundation for the coming year. Reflect on your accomplishments with quiet satisfaction and set mature, realistic goals for the next phase of your journey.",
};
