/**
 * Spirituality Interpretation Blocks
 *
 * Reusable, deterministic text blocks for spirituality predictions.
 * Includes monthly-specific blocks for granular month-by-month guidance.
 */

export const SPIRITUALITY_DASHA_BLOCKS = {
  saturn_active:
    "This is a profound period of spiritual discipline and grounding. Saturn's influence demands structured spiritual practices rather than seeking fleeting mystical experiences. Establish a steady, daily routine of meditation or prayer, even when it feels difficult or dry. The spiritual foundation you build now will serve as an unshakeable anchor during future turbulences. Long-term karmic patterns are being resolved through your patience and dedicated effort. You may feel called to traditional paths, ancient scriptures, or seeking wisdom from elders. True spiritual maturity during this time comes from embracing your worldly duties as acts of sacred service.",
  jupiter_active:
    "A major cycle of spiritual expansion and deeper understanding is unfolding for you. Jupiter brings a natural inclination towards philosophy, higher learning, and seeking universal truths. This is an excellent time to find a spiritual teacher, join a study group, or embark on a pilgrimage. Your faith and optimism will naturally strengthen, allowing you to see the divine intelligence working in your life. You are likely to experience moments of profound clarity and a widening of your conscious awareness. Benevolence, charity, and sharing your wisdom with others will accelerate your spiritual growth. The universe is actively supporting your quest for meaning and purpose.",
  mars_active:
    "Your spiritual journey takes on an active, dynamic, and sometimes intense quality. You may feel a burning desire to push past your current limitations and engage in rigorous physical or energetic practices like dynamic yoga, martial arts, or intense breathwork. Mars encourages you to confront your inner shadows and fight for your spiritual liberation with courage. Be mindful of spiritual impatience or becoming overly aggressive in your beliefs. This period is about transmuting raw, instinctual energy into higher spiritual power. Taking decisive action towards your soul's calling is favored. You have the spiritual warrior's energy to overcome significant inner obstacles.",
  venus_active:
    "Your path to the divine is illuminated through devotion, beauty, and harmony. Venus softens the spiritual journey, encouraging you to connect with the sacred through art, music, nature, and loving relationships. Practices like chanting (Bhakti yoga), creating sacred art, or cultivating a beautiful altar will resonate deeply with you now. You will likely find spiritual realization not through harsh discipline, but through cultivating a state of joy and appreciation for life's blessings. Healing past relational wounds becomes a powerful spiritual practice. Sensual and aesthetic experiences can become gateways to mystical states of awareness. Embrace the path of love and devotion.",
  mercury_active:
    "Your spiritual growth is strongly linked to intellect, study, and communication. Mercury's energy drives you to analyze, question, and understand the philosophical frameworks of different spiritual traditions. It is an excellent time for journaling, reading sacred texts, engaging in spiritual debates, or studying esoteric sciences like astrology or numerology. You may find that writing or speaking about your spiritual insights helps solidify them. Beware of overthinking or getting lost in spiritual concepts without practical application. True wisdom now comes from connecting your analytical mind with your deeper intuition. Seek out teachings that offer clear, logical frameworks for spiritual development.",
  rahu_active:
    "This is a period of intense, often unconventional, spiritual hunger and exploration. Rahu pushes you to look beyond traditional religious boundaries and seek out esoteric, mystical, or foreign spiritual practices. You might feel drawn to powerful energetic awakenings, shamanic practices, or sudden shifts in your belief systems. While this can lead to rapid expansion of consciousness, be cautious of spiritual illusions or seeking quick fixes. Grounding practices are essential to balance this volatile and highly active psychic energy. You are breaking free from ancestral conditioning and discovering your unique, unorthodox path to the divine. Embrace the unknown with discernment.",
  ketu_active:
    "Ketu brings a profound cycle of spiritual detachment, introspection, and karmic clearing. You may feel a strong urge to withdraw from the material world, seek solitude, and dive deep into your own consciousness. This is a highly favorable period for deep meditation, retreats, and releasing attachments to past identities and desires. You are being called to surrender what no longer serves your soul's evolution, which can sometimes feel like a loss, but is actually a liberation. Mystical experiences, vivid dreams, and sudden intuitive insights are highly likely. The veil between the physical and spiritual realms is thin for you now. True peace is found in letting go and trusting the divine flow.",
  sun_active:
    "Your spiritual path is centered around self-realization, sovereignty, and illuminating your true inner nature. The Sun's energy encourages you to step into your spiritual power and align your life completely with your highest truth. You may feel called to leadership roles within spiritual communities or simply to shine your light more brightly in the world. Practices that connect you with solar energy, visualization, and strengthening your sense of 'I AM' are highly beneficial. You are shedding false egos and discovering the radiant, eternal soul at your core. Integrity, authenticity, and living by your own spiritual authority are your guiding principles.",
  moon_active:
    "Your spirituality becomes deeply emotional, intuitive, and receptive during this cycle. The Moon calls you to connect with the divine mother, lunar energies, and the fluid nature of your own soul. Your psychic sensitivity and empathy are heightened, making this a powerful time for inner child work, healing ancestral trauma, and working with intuition. Water-based rituals, dream journaling, and nurturing yourself and others become profound spiritual practices. You may experience fluctuating spiritual moods, which is a natural part of this cyclical energy. True spiritual strength now comes from your ability to compassionately hold space for your own and others' emotional depths. Trust the whispers of your soul.",
};

export const SPIRITUALITY_HOUSE_BLOCKS = {
  saturn_1st:
    "Spiritual discipline reflects heavily in your personal identity. You are learning to embody your spiritual principles in your everyday actions, presenting a serious, grounded, and ethical face to the world. Your personal presence becomes a testament to the inner work you have done.",
  saturn_12th:
    "This is a powerful placement for deep, isolated spiritual retreats and facing hidden fears. You are restructuring your subconscious mind and clearing long-held karmic debts. Solitude is not loneliness now, but a necessary crucible for profound spiritual maturation.",
  jupiter_9th:
    "Your natural inclination toward higher wisdom is incredibly strong. You are drawn to philosophical study, long journeys of spiritual discovery, and interacting with diverse belief systems. Your faith is expanding, and you may find yourself stepping into the role of a teacher or guide for others.",
  jupiter_12th:
    "You have a profound, almost hidden spiritual protection. Your connection to the divine is private but incredibly deep, often manifesting through vivid dreams, meditation, or charitable acts behind the scenes. You are learning to trust the unseen universe completely.",
  mars_8th:
    "Your spiritual journey involves intense transformation and confronting the mysteries of life and death. You have the energetic capacity to dive into occult or esoteric studies and emerge empowered. Your path is not for the faint of heart, requiring you to actively burn through spiritual blockages.",
  venus_6th:
    "Your spirituality is best expressed through acts of service and healing. You find the divine in the details of daily routines and in helping others improve their well-being. Cultivating a beautiful, harmonious environment for your daily practices is essential for your spiritual peace.",
  sun_9th:
    "Your soul's purpose is intimately tied to seeking truth and sharing it with the world. You illuminate complex spiritual concepts for yourself and others. Your faith is a source of immense personal pride and vitality, driving you to explore the higher meaning of your existence.",
  moon_4th:
    "Your spiritual foundation is deeply connected to your home, ancestry, and inner emotional sanctum. You find the greatest peace in private, nurturing spiritual practices within your own sacred space. Healing family lineage and connecting with your roots brings profound spiritual fulfillment.",
  mercury_8th:
    "Your mind is drawn to the hidden, the psychological, and the esoteric dimensions of spirituality. You excel at researching life's mysteries and communicating complex, transformative ideas. Your spiritual growth comes through deep, investigative analysis of your own psyche.",
  rahu_12th:
    "You have an insatiable curiosity for mystical experiences and altered states of consciousness. You may be drawn to foreign spiritual traditions or unusual meditation techniques. While this placement offers access to deep insights, grounding is crucial to avoid becoming unmoored by the vastness of the unseen realms.",
};

export const SPIRITUALITY_SIGN_BLOCKS = {
  jupiter_sagittarius:
    "Your spiritual philosophy is vast, optimistic, and inclusive. You seek the highest truth and possess a natural, buoyant faith that inspires those around you. You are a natural seeker, always looking toward the horizon of higher understanding.",
  jupiter_pisces:
    "Your spirituality is characterized by deep compassion, mysticism, and a sense of universal oneness. You easily dissolved the boundaries between yourself and the divine. Your intuitive connection to the unseen world is one of your greatest spiritual gifts.",
  saturn_aquarius:
    "You approach spirituality with a blend of traditional discipline and progressive thinking. You are interested in how spiritual laws govern the collective and may feel called to participate in community-based spiritual or humanitarian efforts.",
  ketu_scorpio:
    "You have a profound, instinctual understanding of life's deepest mysteries. Your path involves radically shedding old skins and embracing the transformative power of spiritual rebirth. Superficial spirituality will not satisfy your soul's intense craving for truth.",
  moon_cancer:
    "Your spiritual life is incredibly rich, sensitive, and emotionally resonant. You connect best with the divine through feeling, intuition, and heartfelt devotion. Your empathic nature allows you to deeply understand the spiritual needs of others.",
};

export const SPIRITUALITY_PERSONAL_YEAR_BLOCKS: Record<number, string> = {
  1: "This year marks a powerful spiritual new beginning. You are initiating a fresh cycle of self-discovery and defining your independent spiritual path. It is a time to plant seeds for the spiritual person you wish to become. Trust your inner voice and take bold steps toward your soul's calling. The energy supports breaking free from old religious or spiritual conditioning to find your authentic truth. Focus on developing your individual connection to the divine.",
  2: "Your spiritual focus shifts toward harmony, partnership, and receptive intuition. You will find spiritual growth through peaceful interactions, counseling, and deep listening. It is a year to balance the masculine and feminine energies within yourself. Patience is key; spiritual insights may arrive slowly and subtly. Collaborating with a spiritual partner or joining a supportive community can be highly beneficial. Pay attention to your dreams and subtle intuitive nudges.",
  3: "This is a year of joyful, expressive spirituality. You are encouraged to connect with the divine through creativity, art, music, and joyful communication. Your spiritual path should not feel heavy this year; it should feel uplifting and celebratory. Sharing your spiritual insights through speaking, writing, or art will amplify your growth. You may experience a lightening of your spirit and a greater capacity to see the beauty in all things. Embrace the concept of 'lila' or divine play.",
  4: "Your spiritual journey requires discipline, structure, and grounding this year. It is time to build a solid foundation for your spiritual practices. Committing to a regular, daily routine—whether it's meditation, yoga, or study—will yield profound results. Avoid seeking glamorous mystical experiences; focus instead on the practical application of spiritual principles in your daily life. The hard work you put into your inner life now will create lasting stability. You are building your spiritual temple.",
  5: "Expect expansion, adventure, and unexpected shifts in your spiritual perspective. This year challenges your existing belief systems and encourages you to explore varying philosophies or traditions. You may feel a strong urge to travel for spiritual purposes or to try radically different practices. Flexibility and an open mind are your greatest assets. Allow yourself to break free from rigid spiritual routines and embrace the dynamic, unpredictable nature of the divine. This is a year of spiritual liberation.",
  6: "Your spirituality finds its deepest expression through love, service, and nurturing others. Healing—both offering it and receiving it—is a central theme this year. You will find profound connection to the divine by caring for your family, your community, or those in need. Creating a beautiful, peaceful sanctuary in your home supports your inner growth. Your spiritual practices should focus on cultivating compassion, forgiveness, and unconditional love. You are learning to see the divine in everyone.",
  7: "This is the ultimate year for deep introspection, solitude, and inner spiritual work. The external world may hold less appeal as you feel a strong calling to withdraw and seek answers within. It is an excellent time for meditation retreats, studying deep philosophical or esoteric subjects, and resting your spirit. You are integrating the lessons of the past years and refining your connection to higher consciousness. Honor your need for quiet time and give yourself space to simply 'be'. Your intuition and inner wisdom are highly active.",
  8: "You are learning to integrate spiritual principles with material success and personal power. This year is about achieving mastery and applying your spiritual understanding to manifest your goals in the real world. You may face tests of integrity and the challenge of balancing ambition with ethical responsibility. True spiritual power comes from recognizing that you are a co-creator with the universe. Money and resources can be viewed as energy to be used for the highest good. Step confidentially into your spiritual authority.",
  9: "This year represents the culmination and completion of a major spiritual cycle. It is a time of clearing, letting go, and deep surrender. You may need to release old beliefs, attachments, or spiritual identities that no longer serve your evolution. Forgiveness, both of yourself and others, is the key to moving forward. You are emptying your cup so it may be filled anew in the coming cycle. Compassion and humanitarian concerns may take precedence. Embrace the process of dissolution with grace and trust.",
};

export const SPIRITUALITY_MONTHLY_BLOCKS: Record<number, string> = {
  1: "January sets a focused, disciplined tone for your spiritual practices. It is an excellent month to establish your intentions for the year and commit to a structured routine. You may feel a desire to simplify your life to create more space for inner reflection. Patience and consistency in your daily meditations or prayers will ground you. Seek silence and solitude to connect with your inner guidance.",
  2: "February encourages a more intuitive, receptive approach to your spiritual journey. Pay close attention to your dreams, synchronicities, and subtle emotional shifts. Your empathic abilities are heightened, making this a good time for heart-centered practices and connecting with others on a soul level. Practice unconditional love and forgiveness. Let your intuition guide your spiritual choices.",
  3: "March brings a surge of active, dynamic spiritual energy. You may feel inspired to take bold steps, try a new intense physical practice like dynamic yoga, or passionately advocate for a spiritual cause. This is a month the push through inner resistance and overcome spiritual lethargy. Courageously face any inner shadows. Your drive for self-realization is strong and focused.",
  4: "April grounds your spiritual energy into practical reality. Focus on how your spiritual beliefs are reflected in your daily life, your environment, and your relationship with nature. Spending time outdoors, gardening, or walking meditations are highly beneficial. You may find comfort in traditional practices and establishing a sense of deep inner security. Appreciate the simple, tangible blessings in your life.",
  5: "May accelerates your spiritual growth through learning, communication, and intellectual exploration. You may find yourself drawn to reading new spiritual texts, attending workshops, or engaging in stimulating philosophical discussions. It is a month of expanding your mind and breaking free from rigid mental constructs. Seek out new perspectives and be willing to question your own assumptions. Your curiosity is your spiritual guide.",
  6: "June emphasizes deep inner emotional healing and connecting with the concept of the divine mother or divine feminine. Your spirituality is highly personal and tied to your sense of internal safety. Practices that nurture your soul, such as inner child work, journaling, or creating a sacred space at home, will be profound. Allow yourself to feel your emotions fully as a path to spiritual clearing. Seek comfort in familiar spiritual routines.",
  7: "July encourages you to express your spirituality with confidence, joy, and a sense of personal sovereignty. You are called to shine your inner light and perhaps take on a leadership or teaching role within your community. Connect with solar energy and practices that build your spiritual self-esteem. Creative expression can become a powerful form of worship. Celebrate your unique spiritual journey.",
  8: "August demands a meticulous, service-oriented approach to your spirituality. True devotion is found in the details of daily life and in offering practical help to others. You may feel called to refine your spiritual routines, focus on mind-body health, or engage in karma yoga (selfless service). Purity of intention and attention to detail are paramount. Organize your inner life with the same care as your outer life.",
  9: "September focuses on finding spiritual harmony, balance, and the beauty in all things. Your path to the divine is through creating peace within yourself and your relationships. Art, music, and aesthetic appreciation can elevate your consciousness. This is a time to seek the middle way, avoiding extremes in your spiritual practices. Healing past relationship karmas brings profound spiritual liberation.",
  10: "October plunging you into the depths of your psyche for profound spiritual transformation. This is not a month for superficial spirituality; you are called to face the truth, confront your shadows, and release deep-seated fears. Esoteric studies, intense meditation, and psychological self-analysis yield powerful results. Complete surrender to the process of inner alchemy will lead to a sense of spiritual rebirth and empowerment.",
  11: "November expands your spiritual vision and connects you with a higher, more universal perspective. You may feel a strong desire to seek a guru, study profound philosophical truths, or travel for spiritual purposes. Your faith and optimism are renewed. This is a time for expansive, joyful spiritual exploration and sharing your wisdom with others. Trust in the benevolent intelligence of the universe.",
  12: "December is a month of culmination, structure, and taking your spiritual responsibilities seriously. You are asked to integrate the spiritual lessons of the past year and solidify them into wisdom. Solitude and deep contemplation are favored over social spiritual activities. You are building the enduring architecture of your soul. Reflect on your long-term karmic goals and the legacy you wish to leave behind.",
};
